'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const {chromium}=require('playwright'),H=require('./field_workspace_probe_harness.cjs'),controls=require('./custom_control_actions.cjs');
const output=path.resolve(process.argv[2]||'');assert(process.argv[2]&&!output.startsWith(H.root+'/'));
fs.mkdirSync(output,{recursive:true});
const report={scope:'AK field component mock and real temporary Flask SQLite',production_db:false,global_build:false,cases:[],screenshots:[],errors:[],requests:[],downloads:[]};
let state,page,fixtureDir;
async function shot(name){const file=path.join(output,state+'-'+name+'.png');await page.screenshot({path:file,fullPage:false,animations:'disabled'});report.screenshots.push(file);
  const geo=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,dialogs:Array.from(document.querySelectorAll('[role=dialog]')).filter(el=>el.getClientRects().length).map(el=>{const r=el.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,position:getComputedStyle(el.parentElement).position,background:getComputedStyle(el).backgroundColor};}),height:innerHeight,
    blankIcons:Array.from(document.querySelectorAll('[data-field-workspace] button[aria-label]')).filter(button=>!button.textContent.trim()&&!button.querySelector('svg>*')).map(button=>button.getAttribute('aria-label')),
    narrowHistory:Array.from(document.querySelectorAll('.field-history')).filter(node=>node.getBoundingClientRect().width<500).length}));
  assert(geo.scroll<=geo.width+1,JSON.stringify(geo));assert(geo.dialogs.every(r=>r.left>=0&&r.right<=geo.width+1&&r.top>=0&&r.bottom<=geo.height+1),JSON.stringify(geo));
  if(geo.dialogs.length){assert.equal(geo.dialogs[0].position,'fixed','Modal is self-scoped, no harness .plana');assert.notEqual(geo.dialogs[0].background,'rgba(0, 0, 0, 0)');}
  assert.deepEqual(geo.blankIcons,[]);assert.equal(geo.narrowHistory,0);
}
async function run(name,fn){try{await fn();await shot(name);report.cases.push({state,name,passed:true});console.log(state+' '+name+' passed');}catch(error){report.cases.push({state,name,passed:false,error:error.stack});await shot('FAILED-'+name);throw error;}}
async function type(locator,value){await locator.click();await locator.fill('');await locator.type(value,{delay:2});}
async function ready(){await page.getByRole('button',{name:'查看报工 B1 1 Turning',exact:true}).waitFor();}
async function openFirst(){await page.getByRole('button',{name:'查看报工 B1 1 Turning',exact:true}).click();await page.getByRole('table',{name:'逐次报工记录',exact:true}).waitFor();}
async function live(){
  await run('real-read-pagination-and-empty',async()=>{await ready();await page.getByRole('button',{name:'现场下一页'}).click();await page.getByText('共 26 道工序 · 第 2 / 2 页',{exact:true}).waitFor();await page.getByRole('button',{name:'现场上一页'}).click();await ready();await type(page.getByRole('searchbox'),'NO SUCH BATCH');await page.getByRole('button',{name:'查询现场记录'}).click();await page.getByText('当前范围没有任务',{exact:true}).waitFor();await page.getByRole('button',{name:'清除现场筛选'}).click();await ready();});
  await run('real-supplement-actual-resources-and-zero-safe',async()=>{await openFirst();await page.getByRole('button',{name:/^补齐 BG/}).click();await page.getByRole('form',{name:'补齐本次报工'}).waitFor();await type(page.getByRole('spinbutton',{name:'本次完成数量',exact:true}),'3');
    await page.getByLabel('本次实际完工',{exact:true}).fill('2026-09-01T10:00');await type(page.getByRole('spinbutton',{name:'有效工时 (h)',exact:true}),'1.5');
    await controls.select(page.getByLabel('实际设备',{exact:true}),await page.getByLabel('实际设备',{exact:true}).locator('option').nth(1).getAttribute('value'));
    await controls.select(page.getByLabel('实际人员',{exact:true}),await page.getByLabel('实际人员',{exact:true}).locator('option').nth(1).getAttribute('value'));
    await type(page.getByLabel('补齐或更正原因',{exact:true}),'现场交接复核');await type(page.getByLabel('作业备注',{exact:true}),'首批三件');await shot('supplement-input');
    await page.getByRole('button',{name:'保存报工',exact:true}).click();await page.locator('.field-editor').waitFor({state:'hidden'});await page.getByText('已保存并重读最新报工。',{exact:true}).waitFor();await page.getByRole('table',{name:'逐次报工记录',exact:true}).waitFor();assert((await page.getByRole('table',{name:'逐次报工记录',exact:true}).innerText()).includes('1.5'));});
  await run('real-correction-and-history',async()=>{await page.getByRole('button',{name:/^更正 BG/}).click();await type(page.getByRole('spinbutton',{name:'有效工时 (h)',exact:true}),'1.25');await type(page.getByLabel('补齐或更正原因',{exact:true}),'更正有效加工时长');await page.getByRole('button',{name:'保存更正',exact:true}).click();await page.locator('.field-editor').waitFor({state:'hidden'});await page.getByText('已保存并重读最新报工。',{exact:true}).waitFor();await page.getByRole('button',{name:/^录入信息 BG/}).click();await page.getByText('更正有效加工时长',{exact:false}).waitFor();});
  await run('real-template-modal-and-export-full-scope',async()=>{await page.getByRole('button',{name:'报工文件',exact:true}).click();await page.getByRole('dialog',{name:'报工文件',exact:true}).waitFor();await shot('file-modal');for(const [label,name] of [['下载模板','template'],['导出当前范围','export']]){const wait=page.waitForEvent('download');await page.getByRole('button',{name:label,exact:true}).click();const file=await wait;const target=path.join(output,state+'-'+name+'.xlsx');await file.saveAs(target);assert.equal(await file.failure(),null);report.downloads.push(target);}await page.getByRole('button',{name:'取消',exact:true}).click();});
  await run('real-upload-confirm-reimport-conflict',async()=>{await page.getByRole('button',{name:'报工文件',exact:true}).click();await page.getByLabel('报工 XLSX 文件',{exact:true}).setInputFiles(path.join(fixtureDir,'import.xlsx'));await page.getByRole('button',{name:'预检文件',exact:true}).click();await page.getByText('预检通过，尚未写入报工。',{exact:true}).waitFor();await page.getByRole('button',{name:'确认导入',exact:true}).click();await page.getByRole('button',{name:'重读已确认结果',exact:true}).click();await ready();
    await page.getByRole('button',{name:'报工文件',exact:true}).click();await page.getByLabel('报工 XLSX 文件',{exact:true}).setInputFiles(path.join(fixtureDir,'import.xlsx'));await page.getByRole('button',{name:'预检文件',exact:true}).click();await page.getByRole('table',{name:'文件逐行预检'}).getByText('重复',{exact:true}).waitFor();await page.getByRole('button',{name:'确认导入',exact:true}).click();await page.getByRole('button',{name:'重读已确认结果',exact:true}).click();await ready();
    await page.getByRole('button',{name:'报工文件',exact:true}).click();await page.getByLabel('报工 XLSX 文件',{exact:true}).setInputFiles(path.join(fixtureDir,'conflict.xlsx'));await page.getByRole('button',{name:'预检文件',exact:true}).click();await page.getByText('预检未通过，未写入任何报工。',{exact:true}).waitFor();assert(await page.getByRole('button',{name:/^确认导入/}).isDisabled());const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载问题清单',exact:true}).click();const file=await download;await file.saveAs(path.join(output,state+'-errors.xlsx'));await shot('import-conflict');await page.getByRole('button',{name:'取消',exact:true}).click();});
  await run('real-return-and-refresh-retain-identity',async()=>{await page.getByRole('button',{name:'实际甘特',exact:true}).click();await page.locator('#probe-return').click();await ready();await page.getByRole('table',{name:'逐次报工记录',exact:true}).waitFor();const refs=await page.evaluate(()=>probe.nav);assert.match(refs[0].context.task_ref,/^[0-9a-f]{48}$/);assert.equal(refs[0].view,'fieldgantt');assert.equal(refs[0].context.task_ref,refs[1].context.task_ref);await page.getByRole('button',{name:'刷新现场记录'}).click();await ready();});
  await run('real-last-remaining-and-many-report-timeline',async()=>{await page.getByRole('button',{name:'新增本次报工',exact:true}).click();await page.getByLabel('实际开工',{exact:true}).fill('2026-09-01T11:00');await page.getByLabel('本次实际完工',{exact:true}).fill('2026-09-01T13:00');await type(page.getByRole('spinbutton',{name:'有效工时 (h)',exact:true}),'1.75');await page.locator('.field-editor summary').click();
    await controls.select(page.getByLabel('实际设备',{exact:true}),await page.getByLabel('实际设备',{exact:true}).locator('option').nth(1).getAttribute('value'));await controls.select(page.getByLabel('实际人员',{exact:true}),await page.getByLabel('实际人员',{exact:true}).locator('option').nth(1).getAttribute('value'));await page.getByRole('button',{name:'剩余全部完工',exact:true}).click();await page.locator('.field-editor').waitFor({state:'hidden'});await page.getByText('已保存并重读最新报工。',{exact:true}).waitFor();await page.getByRole('table',{name:'逐次报工记录'}).waitFor();assert.equal(await page.getByRole('table',{name:'逐次报工记录'}).locator('tbody>tr').count(),2);
    await page.getByRole('button',{name:'查看报工 B1 4 Turning',exact:true}).click();await page.getByRole('table',{name:'逐次报工记录'}).waitFor();assert.equal(await page.getByRole('table',{name:'逐次报工记录'}).locator('tbody>tr').count(),6);await page.getByRole('button',{name:'作业时间线',exact:true}).click();assert.equal(await page.locator('.field-timeline-track i').count(),7);await shot('many-reports-timeline');});
  await run('real-legacy-complete-explicit-supplement',async()=>{await page.getByRole('button',{name:'查看报工 B1 3 Turning',exact:true}).click();await page.getByText('原始执行事实 · 2 条',{exact:true}).click();await page.getByRole('button',{name:'补齐原始完工记录',exact:true}).click();await type(page.getByRole('spinbutton',{name:'本次完成数量',exact:true}),'10');await page.getByLabel('实际开工',{exact:true}).fill('2026-09-01T08:00');await type(page.getByRole('spinbutton',{name:'有效工时 (h)',exact:true}),'1.5');await controls.select(page.getByLabel('实际设备',{exact:true}),await page.getByLabel('实际设备',{exact:true}).locator('option').nth(1).getAttribute('value'));await controls.select(page.getByLabel('实际人员',{exact:true}),await page.getByLabel('实际人员',{exact:true}).locator('option').nth(1).getAttribute('value'));await type(page.getByLabel('补齐或更正原因',{exact:true}),'逐项核对原始完工单');await page.getByRole('button',{name:'保存报工',exact:true}).click();await page.locator('.field-editor').waitFor({state:'hidden'});await page.getByText('已保存并重读最新报工。',{exact:true}).waitFor();await page.getByRole('table',{name:'逐次报工记录'}).waitFor();assert((await page.locator('.field-detail').textContent()).includes('已有旧完工事实'));});
}
async function mock(origin){
  await page.goto(origin+'/?mock=1&theme='+state.split('-').at(-1));await ready();
  await run('mock-unknown-original-request-lock',async()=>{await openFirst();await page.getByRole('button',{name:/^更正 BG/}).first().click();await type(page.getByLabel('作业备注',{exact:true}),'待核实写入');await type(page.getByLabel('补齐或更正原因',{exact:true}),'模拟中断校验');await page.getByRole('button',{name:'保存更正',exact:true}).click();await page.getByRole('button',{name:'核实原请求'}).waitFor();assert(await page.getByRole('button',{name:'刷新现场记录'}).isDisabled());assert(await page.getByRole('button',{name:'现场下一页'}).isDisabled());assert(await page.getByRole('button',{name:'取消',exact:true}).isDisabled());const key=await page.evaluate(()=>probe.writes[0].body.request_key);await page.getByRole('button',{name:'核实原请求'}).click();assert((await page.evaluate(()=>probe.lookups)).every(value=>value===key));
    page.on('dialog',dialog=>dialog.accept());await page.reload();await page.getByRole('button',{name:'核实原请求'}).waitFor();assert(await page.getByRole('button',{name:'刷新现场记录'}).isDisabled());assert.equal(await page.evaluate(()=>probe.writes.length),0);assert((await page.evaluate(()=>probe.lookups)).every(value=>value===key));
    await page.evaluate(()=>{window.mockReceipt={ok:true,result:'committed',data:{rows:[],summary:{total:1,changed:1,unchanged:0},operation_refs:[]},receipt_ref:'mock-terminal',replayed:true,warnings:[]};});await page.getByRole('button',{name:'核实原请求'}).click();await page.getByRole('button',{name:'重读已确认结果'}).click();assert.equal(await page.evaluate(()=>sessionStorage.getItem('aps_workbench_resource_pending_v1_execution')),null);
  });
  await run('mock-read-failure-not-empty',async()=>{await page.evaluate(()=>{window.mockReadFailure=true;});await page.getByRole('button',{name:'刷新现场记录'}).click();await page.getByText('模拟读取失败',{exact:true}).waitFor();assert.equal(await page.getByText('当前范围没有任务',{exact:true}).count(),0);await page.getByText('现场任务尚未读取',{exact:true}).waitFor();await page.evaluate(()=>{window.mockReadFailure=false;});await page.getByRole('button',{name:'重读现场任务'}).click();await ready();});
  await run('mock-projection-wrong-identity-rejected',async()=>{await page.evaluate(()=>{window.mockWrongProjection=true;});await page.getByRole('button',{name:'刷新现场记录'}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByRole('button',{name:'查看报工 B1 1 Turning',exact:true}).count(),0);await page.evaluate(()=>{window.mockWrongProjection=false;});await page.getByRole('button',{name:'重读现场任务'}).click();await ready();});
}
async function startBackend(index){const child=spawn(path.join(H.root,'.venv/bin/python'),['-m','tests.workbench.field_workspace_probe_server',path.join(output,'db-'+index)],{cwd:H.root,stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',chunk=>stderr+=chunk);const ready=await new Promise((resolve,reject)=>{let text='';child.stdout.on('data',chunk=>{text+=chunk;const line=text.split('\n')[0];try{resolve(JSON.parse(line));}catch{}});child.on('exit',code=>reject(new Error('Fixture exited '+code+': '+stderr)));});return{child,...ready};}
async function main(){let browser;try{browser=await chromium.launch({executablePath:process.env.WORKBENCH_BROWSER,headless:true});report.browser=browser.version();assert.match(report.browser,/^109\./);let index=0;
 for(const size of [{width:1920,height:1080},{width:1392,height:924}])for(const theme of ['light','dark']){state=size.width+'x'+size.height+'-'+theme;const backend=await startBackend(++index),server=H.createServer(backend.url,report);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port,context=await browser.newContext({viewport:size});
  try{fixtureDir=path.dirname(backend.db);page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',error=>report.errors.push({state,message:error.message}));page.on('response',response=>{if(response.url().includes('/api/'))report.requests.push({state,url:response.url(),status:response.status()});});await page.goto(origin+'/?theme='+theme);await live();await mock(origin);}finally{await context.close();await new Promise(resolve=>server.close(resolve));backend.child.kill('SIGTERM');await new Promise(resolve=>backend.child.once('exit',resolve));}}
 assert.deepEqual(report.errors,[]);
 }catch(error){report.error=error.stack;process.exitCode=1;}finally{if(browser)await browser.close();fs.writeFileSync(path.join(output,'field-probe.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({output,cases:report.cases.length,failed:report.cases.filter(row=>!row.passed).length,error:report.error}));}}
main();
