'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
global.window = {};
vm.runInThisContext(fs.readFileSync(path.resolve(__dirname, '../../frontend/workbench/app/ProcessRouteDraft.js'), 'utf8'));
const D = window.ProcessRouteDraft, row = (seq, name) => ({ seq: String(seq), op_type_name: name });
const before = [row(10, '车削'), row(20, '热处理'), row(30, '检验')];
const latest = before.concat(row(40, '精磨'));
assert.deepEqual(D.resolve(D.merge(before, before, latest), {}), latest);
assert.deepEqual(D.resolve(D.merge(before, [row(10, '粗车'), ...before.slice(1)], latest), {}), [row(10, '粗车'), ...latest.slice(1)]);
assert.deepEqual(D.resolve(D.merge(before, before, before.filter(item => item.seq !== '20')), {}), before.filter(item => item.seq !== '20'));
assert.deepEqual(D.resolve(D.merge(before, before.filter(item => item.seq !== '20'), latest), {}), latest.filter(item => item.seq !== '20'));
const conflict = D.merge(before, [row(10, '粗车'), ...before.slice(1)], [row(10, '精车'), ...latest.slice(1)]);
assert.equal(conflict.conflicts.length, 1);
assert.throws(() => D.resolve(conflict, {}), /逐项选择/);
assert.deepEqual(D.resolve(conflict, { 10: 'local' }), [row(10, '粗车'), ...latest.slice(1)]);
assert.deepEqual(D.resolve(conflict, { 10: 'latest' }), [row(10, '精车'), ...latest.slice(1)]);
const deleted = D.merge(before, before.filter(item => item.seq !== '20'), [before[0], row(20, '退火'), before[2]]);
assert.equal(deleted.conflicts.length, 1);
assert.deepEqual(D.resolve(deleted, { 20: 'local' }), before.filter(item => item.seq !== '20'));
const added = D.merge(before, latest, before.concat(row(40, '镀层')));
assert.equal(added.conflicts.length, 1);
assert.deepEqual(D.resolve(added, { 40: 'latest' }), before.concat(row(40, '镀层')));
assert.equal(D.serialize([row(10, '3D打印'), row(20, 'Heat treatment'), row(30, '镀层;"检验"')]), '10: 3D打印；20: Heat treatment；30: "镀层;""检验"""');
assert.equal(D.resolve(D.merge([], [row('9223372036854775807', '末序')], [row(1, '首序')]), {})[1].seq, '9223372036854775807');
console.log('route draft merge/serialization: 14 assertions passed');
