/* Real components, isolated mock adapters, real pending namespace. No product build. */
'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http'), crypto = require('node:crypto');
const { chromium } = require('playwright'), { compile } = require('../../scripts/workbench/compile.cjs');
const root = path.resolve(__dirname, '../..'), output = process.argv[2];
if (!output) throw new Error('Pass a temporary artifact directory');
fs.mkdirSync(output, { recursive: true });
const files = ['WorkbenchFormat.js', 'WorkbenchTerms.js', 'WorkbenchReferences.jsx', 'WorkbenchGuards.js', 'resource-api.js', 'resource-contract.js', 'resource-session.js', 'ResourceControls.jsx', 'WorkbenchGuardHost.jsx', 'ResourceTableFilterModel.js', 'ResourceTables.jsx',
  'ResourceDetailRelations.jsx', 'ResourceForms.jsx', 'ResourceMaterialContract.js', 'ResourceMaterialPreview.jsx',
  'WorkbenchControlBridge.js', 'WorkbenchControlStyles.jsx', 'WorkbenchSelectMenu.jsx', 'WorkbenchDatePickerModel.js', 'WorkbenchDatePicker.jsx', 'WorkbenchControls.jsx', 'WorkbenchListControls.jsx', 'WorkbenchNumberControls.jsx',
  'ProcessContract.js', 'ProcessActionContract.js', 'ProcessActionPreview.jsx', 'ProcessFileContract.js', 'ProcessFilePreview.jsx', 'ProcessFileActions.jsx', 'ProcessControls.jsx',
  'ProcessStageEditor.jsx', 'ProcessSourceEditor.jsx', 'ProcessHoursEditor.jsx', 'ProcessRouteEntry.jsx', 'ProcessDetail.jsx'];
const styleSources = JSON.parse(fs.readFileSync(path.join(root, 'scripts/workbench/build-order.json'), 'utf8')).styles.map(name => {
  const file = 'frontend/workbench/app/styles/' + name; return { path: file, code: fs.readFileSync(path.join(root, file), 'utf8') };
});
const workspaceCSS = styleSources.map(row => row.code).join('\n');
const sources = files.map(file => ({ path: 'frontend/workbench/app/' + file, code: fs.readFileSync(path.join(root, 'frontend/workbench/app', file), 'utf8') }));
const compiled = compile({ babel_path: path.join(root, 'frontend/workbench/prototype/ui_kits/workbench/assets/vendor/babel-7.29.0.min.js'), sources, check_combined: true });
const scripts = new Map(compiled.outputs.map((item, index) => ['/fixture/' + files[index] + '.js', item.code]));
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'static/workbench/asset-manifest.json')));
const assets = new Map(manifest.files.map(item => ['/static/' + item.path, { ...item, bytes: fs.readFileSync(path.join(root, 'static', item.path)) }]));
const staticScripts = manifest.scripts.filter(file => file.startsWith('workbench/vendor/') || file.startsWith('workbench/assets/foundation-'));
const fixture = `
const R=n=>n.toString(16).padStart(48,'0'), T=n=>String(n).padEnd(32,'s'), copy=x=>JSON.parse(JSON.stringify(x));
const stamp=state=>({state,confirmed_at:state==='confirmed'?'2026-09-09T12:00:00':null,confirmed_by:null});
const caps={route_preview:true,stage_confirm:true,create:false,delete:false,import:true,export:true};
let f,viewRoot;
function context(action){return {write_token:'t'.repeat(32),capabilities:{[action]:true},blocked_reasons:[]};}
function env(data){return {ok:true,schema_version:1,data,meta:{source:'production',time_basis:'factory_local',snapshot_ref:T(f.revision),request_ref:'mock',as_of:'2026-09-09T12:00:00'},warnings:[]};}
function part(stage='ready',ref=R(1)) {return {ref,business_code:'PART-001',label:ref===R(1)?'原零件':'新对象',status:null,
  fields:{route_raw:'5Turn10Turn',route_parsed:'yes',remark:'原零件备注'},relationships:{operation_count:2,batch_count:7,internal_count:2,external_count:0,unclassified_count:0},issues:[],write_context:context('process.hours_confirm'),capabilities:caps,
  workflow:{origin:'managed',stage,ready:stage==='ready',route:stamp('confirmed'),source:stamp(stage==='source'?'unconfirmed':'confirmed'),hours:stamp(stage==='ready'?'confirmed':stage==='source'?'locked':'unconfirmed')},
  operations:[5,10].map((sequence,i)=>({ref:R(100+i),sequence,label:'Turn',source:'internal',op_type_ref:R(50),op_type_label:'Turn',supplier_ref:null,supplier_label:null,external_group_ref:null,
    setup_hours:0,unit_hours:i+1,external_days:null,external_days_source:null,status:'active',issues:[],confirmation:{source:stamp(stage==='source'?'unconfirmed':'confirmed'),hours:stamp(stage==='ready'?'confirmed':'unconfirmed')}})),external_groups:[]};}
function persist(){sessionStorage.setItem('pd-server',JSON.stringify({spec:f.spec,part:f.part,revision:f.revision,receipt:f.receipt,commands:f.commands}));}
function receiptFault(value,fault){const r=copy(value);if(fault==='partial')r.result='partial';if(fault==='kind')r.data.kind='other';if(fault==='unknown')return {ok:true,state:'not_recorded',receipt:null,may_be_in_flight:true};
  if(fault==='missing')delete r.data.affected_refs;if(fault==='foreign'){r.data.rows[0].entity_ref=R(999);r.data.affected_refs=[R(999)];}if(fault==='stage')r.data={entity_ref:R(1),stage:'hours'};return r;}
function adapter(){const base=APSResourceAPI.create('process');return {...base,
  detail:async(kind,ref,signal)=>{f.reads.push({type:'detail',kind,ref});let value=env(copy(ref===R(1)?f.part:part('ready',ref)));
    if(f.commands.length&&f.spec.failRead)throw APSResourceContract.failure('MOCK detail unavailable');
    if(f.commands.length&&f.spec.deleted)throw APSResourceContract.failure('原零件引用已删除');
    if(f.commands.length&&f.spec.wrongRead)value.data={...value.data,ref:R(999),label:'WRONG ENTITY'};
    if(f.commands.length&&f.spec.holdRead)await new Promise(resolve=>f.releaseRead=resolve);
    if(!f.commands.length&&f.spec.holdInitial)await new Promise(resolve=>f.releaseInitial=resolve);
    return value;},
  routePreview:async(ref,body)=>{f.reads.push({type:'routePreview',ref,body});return env({part_ref:ref,mode:body.mode,route_raw:body.route_raw,normalized_input:body.route_raw,can_confirm_route:true,
    operations:[],diagnostics:[],counts:{operations:0,recognized:0,unknown:0},baseline:{operation_count:2,external_group_count:0,has_published_template:true},changes:{added:[],removed:[],retained:[],same_sequence_changed:[]},affected_groups:[],write_context:context('process.route_confirm')});},
  choices:async(kind,scope)=>{f.reads.push({type:'choices',kind,scope});return env({entities:[{ref:R(51),business_code:'OP-2',label:'Replacement',status:null,fields:{category:'internal'},relationships:{},issues:[],write_context:null}],page:{number:1,size:scope.size,total:1,pages:1,sort:[]}});},
  filePreview:async(kind,mode,body)=>{const request=body instanceof FormData?Object.fromEntries([...body.entries()].map(([key,value])=>[key,key==='file'?value.name:value])):copy(body);f.reads.push({type:'file',kind,mode,request});
    if(mode==='export')return env({kind,export_ref:'e'.repeat(32),expires_at:new Date(Date.now()+60000).toISOString(),selection:body.selection,scope:body.scope,target_ref:body.target_ref,format:body.format,row_count:kind==='hours'?2:1,part_count:1,columns:[{key:'business_code',label:'图号'}]});
    const field=kind==='route'?'route_raw':'unit_hours',before=kind==='route'?f.part.fields.route_raw:f.part.operations[0].unit_hours,after=kind==='route'?'5Fresh10Fresh':7;
    return env({kind,operation:'process_'+kind+'_import.confirm',preview_ref:'p'.repeat(32),expires_at:new Date(Date.now()+60000).toISOString(),commit_policy:'atomic',can_confirm:true,
      format:body.get('format'),mode:'upsert',template_version:1,file_sha256:'a'.repeat(64),instructions:'仅原零件记录。',zero_review_required:false,scope:{},affected_groups:[],...(kind==='hours'?{skipped_count:0,skipped_refs:[],skipped_rows:[]}:{}),
      columns:[{key:'business_code',label:'图号'},{key:field,label:kind==='route'?'路线文字':'单件工时'}],summary:{new:0,update:1,unchanged:0,delete:0,rejected:0},write_context:context('process_'+kind+'_import.confirm'),
      rows:[{row:2,result:'update',entity_ref:R(1),business_code:'PART-001',before:{business_code:'PART-001',[field]:before},after:{business_code:'PART-001',[field]:after},changes:{[field]:{before,after}},reference_count:7,requires_confirmation:true,errors:[],route_summary:kind==='route'?{counts:{operations:2,recognized:2,unknown:0},diagnostics:[],can_confirm_route:true}:null,...(kind==='hours'?{sequence:5}:{})}]});},
  fileDownload:async(kind,template,query)=>{f.reads.push({type:'download',kind,template,query});return {blob:new Blob(['图号,名称\\nPART-001,原零件\\n'],{type:'text/csv'}),contentType:'text/csv',disposition:'attachment; filename="detail.csv"'};},
  command:async(kind,action,ref,body)=>{f.commands.push({kind,action,ref,body:copy(body)});if(f.spec.holdCommand)await new Promise(resolve=>f.releaseCommand=resolve);
    if(kind==='process'){f.part.workflow.stage='ready';f.part.workflow.ready=true;f.part.workflow.hours=stamp('confirmed');f.part.operations.forEach(row=>Object.assign(row,body.input.operations.find(item=>item.ref===row.ref)));f.receipt={ok:true,result:'committed',replayed:false,receipt_ref:'stage-receipt',warnings:[],data:{entity_ref:R(1),stage:'hours'}};}
    else {const fileKind=kind==='process_route_import'?'route':'hours';f.part.operations[0].unit_hours=7;f.part.operations[0].setup_hours=4;f.part.operations[1].unit_hours=8;f.part.operations.forEach(row=>row.confirmation.hours=stamp('unconfirmed'));f.part.workflow.hours=stamp('unconfirmed');f.part.workflow.ready=false;f.part.workflow.stage='hours';
      if(fileKind==='route'){f.part.fields.route_raw='5Fresh10Fresh';f.part.operations.forEach(row=>{row.label='Fresh';row.op_type_label='Fresh';row.confirmation.source=stamp('unconfirmed');});f.part.workflow.source=stamp('unconfirmed');f.part.workflow.hours=stamp('locked');f.part.workflow.stage='source';}
      f.receipt={ok:true,result:'committed',replayed:false,receipt_ref:'file-receipt',warnings:[],data:{kind:fileKind,rows:[{row:2,result:'committed',entity_ref:R(1),business_code:'PART-001',...(fileKind==='hours'?{sequence:5}:{})}],summary:{new:0,update:1,unchanged:0,delete:0,rejected:0},affected_refs:[R(1)],...(fileKind==='hours'?{skipped_count:0,skipped_refs:[],skipped_rows:[]}:{} )}};}
    f.revision++;persist();if(f.spec.pending)throw new Error('MOCK lost receipt');const delivered=receiptFault(f.receipt,f.spec.receiptFault);
    if(kind==='process'&&f.spec.stageFault){if(f.spec.stageFault==='foreign')delivered.data.entity_ref=R(999);else if(f.spec.stageFault==='stage')delivered.data.stage='source';else delete delivered.data.stage;}return delivered;},
  lookup:async key=>{f.lookups.push(key);return f.allowLookup?copy(f.receipt):{ok:true,state:'not_recorded',receipt:null,may_be_in_flight:true};}
};}
function Harness(){const [ref,setRef]=React.useState(R(1)),[opened,setOpen]=React.useState(true);window.switchPart=setRef;
  return React.createElement(React.Fragment,null,React.createElement(WorkbenchGuardHost),React.createElement(WorkbenchControlStyles),React.createElement(WorkbenchControls),React.createElement(WorkbenchNumberControls),
    opened?React.createElement(ProcessDetail,{adapter:f.adapter,partRef:ref,onClose:()=>{f.closed++;setOpen(false);},onCommitted:r=>f.committed.push(r)}):React.createElement('p',null,'详情已关闭'));}
window.mountFixture=(spec={},restore=false)=>{if(viewRoot)viewRoot.unmount();if(!restore){sessionStorage.removeItem('aps_workbench_resource_pending_v1_process');sessionStorage.removeItem('pd-server');}
  const stored=restore&&JSON.parse(sessionStorage.getItem('pd-server')||'null');f=window.fixture={spec:stored?stored.spec:spec,part:stored?stored.part:part(spec.stage||'ready'),revision:stored?stored.revision:1,receipt:stored?stored.receipt:null,commands:stored?stored.commands:[],reads:[],lookups:[],committed:[],closed:0};
  f.adapter=adapter();viewRoot=ReactDOM.createRoot(document.getElementById('fixture-root'));viewRoot.render(React.createElement(Harness));};
if(sessionStorage.getItem('aps_workbench_resource_pending_v1_process'))mountFixture({},true);
`;
const html = '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/static/' + manifest.icon + '">' +
  '<script src="/static/' + manifest.theme_script + '"></script>' + manifest.styles.map(file => '<link rel="stylesheet" href="/static/' + file + '">').join('') + '</head><body class="aps-workbench"><div id="fixture-root"></div>' +
  staticScripts.map(file => '<script src="/static/' + file + '"></script>').join('') + [...scripts.keys()].map(file => '<script src="' + file + '"></script>').join('') + '<script>' + fixture + '</script></body></html>';
const server = http.createServer((req, res) => {const name = new URL(req.url, 'http://fixture').pathname;
  if(name === '/') {res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html.replace('</head>', '<style>' + workspaceCSS + '</style></head>'));}
  else if(scripts.has(name)) {res.setHeader('Content-Type','application/javascript');res.end(scripts.get(name));}
  else if(assets.has(name)) {const asset=assets.get(name);res.setHeader('Content-Type',asset.mime);res.end(asset.bytes);}
  else {res.writeHead(404);res.end();}});
const sha = value => crypto.createHash('sha256').update(value).digest('hex');
const report = {scope:'process-detail-files-component-mock',production_persistence_tested:false,compile:{target:compiled.target,global_build:false},sources:sources.map(row=>({path:row.path,sha256:sha(row.code)})),cases:[],screenshots:[],errors:[],external:[]};
let page,variant;
const button = name => page.getByRole('button',{name,exact:true}), check = name => page.getByRole('checkbox',{name,exact:true});
const number = name => page.getByRole('spinbutton',{name,exact:true});
async function mount(spec={}) {await page.evaluate(spec=>mountFixture(spec),spec);await page.locator('.stepper').waitFor();}
async function stage(name) {await page.getByRole('tab',{name:new RegExp(name)}).click();}
async function file(kind='route') {await button('导入'+(kind==='route'?'工艺路线':'工时定额')).click();await button('CSV (.csv)').click();await page.getByLabel('选择'+(kind==='route'?'工艺路线':'工时定额')+'文件',{exact:true}).setInputFiles({name:'detail.csv',mimeType:'text/csv',buffer:Buffer.from('图号,内容\nPART-001,7\n')});await button('开始预检').click();await check('已核对全部修改前后内容，确认这些更新。').check();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(button=>button.textContent==='确认导入'&&!button.disabled));}
async function saved() {await page.getByText('提交已确认，工艺详情已刷新。',{exact:true}).waitFor();}
async function finishHoursReceipt(screenshot=false) {
  await page.getByRole('table',{name:'工时导入结果明细',exact:true}).waitFor();
  assert.match(await page.getByRole('region',{name:'工时导入结果',exact:true}).innerText(), /已导入\s+1\s+行[\s\S]*锁定跳过\s+0\s+行[\s\S]*原值相同\s+0\s+行/);
  const s=await state();assert.equal(s.committed.length,0);assert.equal(s.closed,0);assert(s.pending);
  assert.equal(s.reads.filter(row=>row.type==='detail').length,1,'No parent refresh before receipt acknowledgement');
  assert.equal(await page.getByText('提交已确认，工艺详情已刷新。',{exact:true}).count(),0);
  await oneDialog();if(screenshot)await shot('hours-receipt');await button('完成').click();
}
async function state() {return page.evaluate(()=>({commands:fixture.commands,reads:fixture.reads,lookups:fixture.lookups,committed:fixture.committed,closed:fixture.closed,pending:sessionStorage.getItem('aps_workbench_resource_pending_v1_process')}));}
async function oneDialog() {assert.equal(await page.getByRole('dialog').count(),1);}
async function shot(name) {const geometry=await page.evaluate(()=>{const visible=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden';return {width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,
  dialogs:[...document.querySelectorAll('[role=dialog]')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom};}),overflow:[...document.querySelectorAll('button')].filter(visible).filter(e=>!e.closest('.card-scroll')&&e.scrollWidth>e.clientWidth+2).map(e=>e.textContent)};});
  assert.equal(geometry.dialogs.length,1);assert(geometry.scroll<=geometry.width+1);assert.deepEqual(geometry.overflow,[]);geometry.dialogs.forEach(r=>assert(r.x>=0&&r.y>=0&&r.right<=geometry.width+1&&r.bottom<=geometry.height+1));
  const file=variant+'-'+name+'.png';await page.screenshot({path:path.join(output,file),animations:'disabled'});report.screenshots.push({file,geometry});}
async function caseOf(name,run){try{await run();report.cases.push({variant,name,passed:true});}catch(error){report.cases.push({variant,name,passed:false,error:error.message});await page.screenshot({path:path.join(output,variant+'-'+name+'-failure.png')});throw error;}}
async function cases(){
  await caseOf('detail-export-explicit-scope-snapshot-and-focus',async()=>{await mount();await stage('工艺路线');await shot('detail');await button('导出工艺路线').click();await oneDialog();assert.equal(await page.getByRole('radio').count(),1);assert(await page.getByRole('radio',{name:'当前零件'}).isChecked());await button('CSV (.csv)').click();await button('开始预检').click();await button('下载文件').waitFor();await shot('export');
    const request=(await state()).reads.find(row=>row.type==='file').request;assert.deepEqual(request,{format:'csv',selection:'explicit',scope:{},snapshot_ref:'1'.padEnd(32,'s'),page_size:20,target_ref:'1'.padStart(48,'0'),refs:['1'.padStart(48,'0')]});
    const download=page.waitForEvent('download');await button('下载文件').click();await download;await button('完成').click();await oneDialog();await page.waitForFunction(()=>document.activeElement.tagName==='BUTTON'&&document.activeElement.textContent==='导出工艺路线');assert.equal((await state()).commands.length,0);assert.deepEqual((await state()).reads.find(row=>row.type==='download').query,{export_ref:'e'.repeat(32)});});
  await caseOf('all-stage-drafts-continue-then-explicit-discard',async()=>{await mount();await stage('工时定额');await number('工序 5 单件工时').fill('99');await stage('^2 归属');await check('确认工序 5 归属').uncheck();await stage('工艺路线');await button('录入路线').click();await page.getByRole('textbox',{name:'路线文字'}).fill('5UNSAVED');await button('取消').click();await button('导入工艺路线').click();await shot('discard');await button('继续编辑').click();await button('录入路线').click();assert.equal(await page.getByRole('textbox',{name:'路线文字'}).inputValue(),'5UNSAVED');await button('取消').click();await stage('^2 归属');assert(!(await check('确认工序 5 归属').isChecked()));await stage('工时定额');assert.equal(await number('工序 5 单件工时').inputValue(),'99');
    await button('导入工时定额').click();await button('放弃草稿并打开文件').click();await oneDialog();await button('取消').click();await stage('工时定额');assert.equal(await number('工序 5 单件工时').inputValue(),'1');await stage('^2 归属');assert(await check('确认工序 5 归属').isChecked());await stage('工艺路线');await button('录入路线').click();assert.equal(await page.getByRole('textbox',{name:'路线文字'}).inputValue(),'5Turn10Turn');await button('取消').click();assert.equal((await state()).commands.length,0);});
  await caseOf('file-save-refreshes-every-draft-and-workflow',async()=>{await mount();await stage('工艺路线');await file();await shot('import');await button('确认导入').click();await saved();await oneDialog();assert((await page.getByRole('table',{name:'归属明细'}).innerText()).includes('Fresh'));assert(!(await check('确认工序 5 归属').isChecked()));await stage('工时定额');assert.equal(await number('工序 5 单件工时').inputValue(),'7');assert.equal(await number('工序 10 单件工时').inputValue(),'8');await stage('工艺路线');await button('录入路线').click();assert.equal(await page.getByRole('textbox',{name:'路线文字'}).inputValue(),'5Fresh10Fresh');await button('取消').click();const s=await state();assert.equal(s.commands.length,1);assert.equal(s.committed.length,1);assert.equal(s.pending,null);assert(s.reads.filter(r=>r.type==='detail').every(r=>r.ref==='1'.padStart(48,'0')));assert.equal(s.reads.find(r=>r.type==='file').request.target_ref,'1'.padStart(48,'0'));});
  await caseOf('hours-file-then-stage-save-is-distinct',async()=>{await mount();await stage('工时定额');await file('hours');await button('确认导入').click();await finishHoursReceipt(true);await saved();assert.equal((await state()).committed.length,1);assert.equal(await number('工序 5 单件工时').inputValue(),'7');assert(!(await check('确认工序 5 工时').isChecked()));await check('确认本页已核对工时').check();await button('保存工时').click();await page.getByRole('table',{name:'已就绪工序汇总'}).waitFor();const s=await state();assert.deepEqual(s.commands.map(r=>r.kind),['process_hours_import','process']);assert.equal(s.committed.length,2);assert.equal(s.commands[1].body.input.operations[0].unit_hours,7);});
  await caseOf('saved-read-error-retries-read-only',async()=>{await mount({failRead:true});await stage('工时定额');await file('hours');await button('确认导入').click();await finishHoursReceipt();await button('查询结果').waitFor();assert((await page.getByRole('dialog').innerText()).includes('文件已保存，但刷新零件详情失败'));assert(await number('工序 5 单件工时').isDisabled());assert(await button('导入工时定额').isDisabled());await shot('read-error');await page.evaluate(()=>fixture.spec.failRead=false);await button('查询结果').click();await saved();assert.equal(await number('工序 5 单件工时').inputValue(),'7');assert.equal((await state()).commands.length,1);assert.equal((await state()).committed.length,1);});
  await caseOf('wrong-ref-and-deleted-ref-never-adopt-same-code',async()=>{for(const mode of ['wrongRead','deleted']){await mount({[mode]:true});await stage('工时定额');await file('hours');await button('确认导入').click();await finishHoursReceipt();await button('查询结果').waitFor();assert(!(await page.getByRole('dialog').innerText()).includes('WRONG ENTITY'));assert((await page.getByRole('dialog').innerText()).includes('不能续用同图号的新零件'));assert.equal(await number('工序 5 单件工时').inputValue(),'1');assert(await number('工序 5 单件工时').isDisabled());await button('查询结果').click();assert.equal((await state()).commands.length,1);assert((await state()).reads.filter(r=>r.type==='detail').every(r=>r.ref==='1'.padStart(48,'0')));}});
  await caseOf('pending-locks-close-and-reload-uses-original-key',async()=>{await mount({pending:true});await stage('工时定额');await file('hours');await button('确认导入').click();await button('查询结果').waitFor();const pending=JSON.parse((await state()).pending);assert.equal(Object.keys(pending).sort().join(','),'action,kind,ref,request_key');assert(await button('取消').isDisabled());await page.keyboard.press('Escape');await oneDialog();await shot('pending');await page.reload();await button('查询结果').waitFor();assert.equal((await state()).lookups[0],pending.request_key);assert.equal((await state()).commands.length,1);assert(await button('取消').isDisabled());await page.evaluate(()=>fixture.allowLookup=true);await button('查询结果').click();await finishHoursReceipt();await saved();assert.equal((await state()).pending,null);assert.equal((await state()).commands.length,1);assert((await state()).lookups.every(key=>key===pending.request_key));});
  await caseOf('unknown-or-foreign-file-receipt-remains-locked',async()=>{for(const fault of ['partial','kind','unknown','missing','foreign','stage']){await mount({receiptFault:fault});await stage('工时定额');await file('hours');await button('确认导入').click();await button('查询结果').waitFor();assert(await button('取消').isDisabled());await page.keyboard.press('Escape');await oneDialog();assert.equal((await state()).committed.length,0);assert((await state()).pending);assert.equal(await page.getByText('提交已确认，工艺详情已刷新。',{exact:true}).count(),0);await page.evaluate(()=>fixture.allowLookup=true);await button('查询结果').click();await finishHoursReceipt();await saved();assert.equal((await state()).commands.length,1);assert.equal((await state()).committed.length,1);}});
  await caseOf('sending-and-reread-lock-with-late-result',async()=>{await mount({holdCommand:true,holdRead:true});await stage('工时定额');await file('hours');await button('确认导入').click();await page.waitForFunction(()=>!!fixture.releaseCommand);assert(await button('取消').isDisabled());await page.evaluate(()=>fixture.releaseCommand());await finishHoursReceipt();await page.waitForFunction(()=>!!fixture.releaseRead);assert(await button('关闭详情').isDisabled());assert(await number('工序 5 单件工时').isDisabled());await page.keyboard.press('Escape');await oneDialog();await page.evaluate(()=>fixture.releaseRead());await saved();assert.equal((await state()).commands.length,1);});
  await caseOf('prop-switch-does-not-accept-late-original-detail',async()=>{
    await mount();await stage('工时定额');await file('hours');await button('确认导入').click();await page.getByRole('table',{name:'工时导入结果明细',exact:true}).waitFor();
    const pending=(await state()).pending;await page.evaluate(()=>switchPart(R(2)));await button('查询结果').waitFor();await page.waitForFunction(()=>document.querySelector('.process-detail > .modal-bg .modal-h2').textContent==='PART-001 · 新对象');
    assert(await button('取消').isDisabled());assert((await state()).pending);assert.equal((await state()).pending,pending);assert.equal((await state()).committed.length,0);
    await mount({holdRead:true});await stage('工时定额');await file('hours');await button('确认导入').click();await finishHoursReceipt();await page.waitForFunction(()=>!!fixture.releaseRead);
    assert.equal((await state()).pending,null);assert.equal((await state()).committed.length,1);
    await page.evaluate(()=>{fixture.spec.holdRead=false;switchPart(R(2));});await page.getByRole('dialog',{name:'PART-001 · 新对象',exact:true}).waitFor();await page.evaluate(()=>fixture.releaseRead());
    assert.equal(await page.locator('.process-detail > .modal-bg .modal-h2').textContent(),'PART-001 · 新对象');assert.equal((await state()).pending,null);assert.equal((await state()).committed.length,1);
    assert.equal(await page.getByRole('table',{name:'工时导入结果明细',exact:true}).count(),0);
    await page.evaluate(()=>mountFixture({holdInitial:true}));await page.waitForFunction(()=>!!fixture.releaseInitial);await page.evaluate(()=>{fixture.spec.holdInitial=false;switchPart(R(2));});await page.getByRole('dialog',{name:'PART-001 · 新对象',exact:true}).waitFor();await page.evaluate(()=>fixture.releaseInitial());assert.equal(await page.getByRole('dialog',{name:'PART-001 · 新对象',exact:true}).count(),1);});
  await caseOf('cancel-file-draft-keeps-single-dialog',async()=>{await mount();await stage('工时定额');await file('hours');await button('取消').click();await oneDialog();await button('继续核对').click();await oneDialog();await button('取消').click();await button('放弃导入并关闭').click();await oneDialog();assert.equal((await state()).commands.length,0);assert.equal(await number('工序 5 单件工时').inputValue(),'1');});
  await caseOf('source-picker-not-disabled-by-parent-suspension',async()=>{await mount();await stage('^2 归属');await button('选择工序 5 工种').click();await button('采用 Replacement').waitFor();await oneDialog();assert(!(await button('采用 Replacement').isDisabled()));await button('采用 Replacement').click();assert((await page.getByRole('table',{name:'归属明细'}).innerText()).includes('Replacement'));await oneDialog();});
  await caseOf('stage-wrong-receipt-keeps-original-pending',async()=>{for(const stageFault of ['foreign','stage','missing']){await mount({stage:'hours',stageFault});await check('确认本页已核对工时').check();await button('保存工时').click();await button('查询结果').waitFor();assert(await button('关闭详情').isDisabled());assert.equal((await state()).committed.length,0);assert((await state()).pending);await page.keyboard.press('Escape');await oneDialog();await page.evaluate(()=>fixture.allowLookup=true);await button('查询结果').click();await saved();assert.equal((await state()).commands.length,1);assert.equal((await state()).committed.length,1);}});
}
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;try{browser=await chromium.launch({executablePath:process.env.WORKBENCH_BROWSER,headless:true,args:['--disable-background-networking']});report.browser=browser.version();assert(report.browser.startsWith('109.'));const origin='http://127.0.0.1:'+server.address().port;
  for(const viewport of [{width:1392,height:924},{width:640,height:900}])for(const theme of ['light','dark']){const context=await browser.newContext({viewport});await context.addInitScript(theme=>{localStorage.setItem('aps_theme',theme);localStorage.setItem('aps_kit_theme',theme);},theme);page=await context.newPage();page.setDefaultTimeout(10000);variant=viewport.width+'x'+viewport.height+'-'+theme;
    page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});await page.route('**/*',route=>{if(!route.request().url().startsWith(origin+'/')){report.external.push(route.request().url());return route.abort();}return route.continue();});await page.goto(origin);await cases();await context.close();}
  assert.deepEqual(report.errors,[]);assert.deepEqual(report.external,[]);
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));fs.writeFileSync(path.join(output,'process-detail-files-result.json'),JSON.stringify(report,null,2)+'\n');}
console.log(JSON.stringify({output,browser:report.browser,cases:report.cases.length,screenshots:report.screenshots.length,errors:report.errors,external:report.external}));})().catch(error=>{console.error(error);process.exitCode=1;});
