'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('playwright'),{compile}=require('../../scripts/workbench/compile.cjs');
const root=path.resolve(__dirname,'../..'),output=process.argv[2];assert(output);fs.mkdirSync(output,{recursive:true});
const files=['WorkbenchPageContext.jsx','resource-contract.js','resource-session.js','WorkbenchFormat.js','WorkbenchTerms.js','WorkbenchReferences.jsx','WorkbenchGuards.js','ResourceControls.jsx','WorkbenchGuardHost.jsx','WorkbenchControlBridge.js','WorkbenchControls.jsx','WorkbenchListControls.jsx',
  'ResourceTableFilterModel.js','ResourceTableFilter.jsx','ResourceTableHeader.jsx','ResourceDetailRelations.jsx','ResourceForms.jsx','ResourceTables.jsx','ResourceMetrics.jsx','ResourceRail.jsx','ResourceWorkspace.jsx','ResourceCatalogModel.js','ResourceCatalogEditor.jsx','ResourceCatalog.jsx','WorkbenchControlStyles.jsx','WorkbenchSelectMenu.jsx','WorkbenchNumberControls.jsx'];
const sources=files.map(file=>({path:'frontend/workbench/app/'+file,code:fs.readFileSync(path.join(root,'frontend/workbench/app',file),'utf8')}));
const compiled=compile({babel_path:path.join(root,'frontend/workbench/prototype/ui_kits/workbench/assets/vendor/babel-7.29.0.min.js'),sources,check_combined:true});
const scripts=new Map(compiled.outputs.map((item,i)=>['/fixture/'+files[i]+'.js',item.code]));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'static/workbench/asset-manifest.json'))),assets=new Map(manifest.files.map(row=>['/static/'+row.path,row]));
const styles=fs.readdirSync(path.join(root,'frontend/workbench/app/styles')).filter(file=>file.endsWith('.css')).sort().map(file=>({path:'frontend/workbench/app/styles/'+file,code:fs.readFileSync(path.join(root,'frontend/workbench/app/styles',file),'utf8')}));
const fixture=`
const h=React.createElement,R=n=>n.toString(16).padStart(48,'0');let mounted;
const wc=kind=>({write_token:kind+':'+fixture.version,capabilities:{[kind+'.update']:true,[kind+'.create']:true,[kind+'.delete']:false},blocked_reasons:[]});
const env=data=>({ok:true,schema_version:1,data,meta:{source:'production',time_basis:'factory_local',snapshot_ref:'snapshot-'+fixture.version,request_ref:'test',as_of:'2026-09-15T12:00:00'},warnings:[]});
function entity(kind){return kind==='operator'?{ref:R(1),business_code:'OP1',label:fixture.person,status:fixture.status,fields:{},relationships:{skill_refs:[],skills:[],shift_profile_ref:fixture.shiftRef,shift_profile:fixture.shiftRef?{ref:R(2),label:fixture.shift}:null,machine_authorization_count:0},issues:[],write_context:wc(kind)}:
 {ref:R(2),business_code:'SHIFT1',label:fixture.shift,status:'active',fields:{anchor_date:'2026-09-15',cycle_days:2,pattern:[{day_offset:0,is_rest:false,shift_start:'22:00',shift_end:'06:00'},{day_offset:1,is_rest:true,shift_start:'22:00',shift_end:'06:00'}]},relationships:{operator_count:1},issues:[],write_context:wc(kind)};}
function adapter(){return {
 list:async(kind,scope)=>env({entities:[entity(kind)],page:{number:scope.page,size:scope.size,total:1,pages:1,sort:[]},create_context:wc(kind)}),
 detail:async kind=>{fixture.reads++;return env(entity(kind));},
 choices:async(kind,scope)=>env({entities:kind==='shift_profile'?[entity(kind)]:[],page:{number:scope.page,size:scope.size,total:kind==='shift_profile'?1:0,pages:1,sort:[]}}),
 summary:async()=>env({counts:{part:0,material:0,internal_op_types:0,machine:0,operator:1,external_op_types:0,supplier:0}}),
 command:async(kind,action,ref,body)=>{fixture.writes.push({kind,action,ref,body});if(body.write_token!==kind+':'+fixture.version)return {ok:false,committed:false,error:{code:'stale_write',message:'资料已变化，请刷新最新资料。',fields:[]}};
  if(kind==='shift_profile')fixture.shift=body.input.label||fixture.shift;else{if(body.input.label)fixture.person=body.input.label;if(body.input.relationships&&Object.hasOwn(body.input.relationships,'shift_profile_ref'))fixture.shiftRef=body.input.relationships.shift_profile_ref;}
  fixture.version++;return {ok:true,result:'committed',receipt_ref:'test-receipt-'+fixture.version,data:{entity_ref:ref},warnings:[]};}
};}
window.mountFixture=()=>{if(mounted)mounted.unmount();window.fixture={version:1,person:'原人员',status:'active',shift:'原两日班',shiftRef:R(2),writes:[],reads:0};
 function Harness(){const [catalog,setCatalog]=React.useState(null);const base=React.useMemo(()=>({...adapter(),openCatalog:(kind,request)=>{setCatalog({kind,request});return {state:'opened'};}}),[]),cat=React.useMemo(adapter,[]);
 return h(React.Fragment,null,h(WorkbenchControlStyles),h(WorkbenchControls),h(WorkbenchNumberControls),h(WorkbenchGuardHost),h(ResourceWorkspace,{adapter:base,initialContext:{source:'production',kind:'operator',entity_ref:R(1)}}),
  catalog&&h(ResourceCatalog,{kind:catalog.kind,adapter:cat,onClose:()=>{setCatalog(null);catalog.request.onClosed();},onCommitted:result=>{setCatalog(null);catalog.request.onCommitted(result);}}));}
 mounted=ReactDOM.createRoot(document.getElementById('root'));mounted.render(h(Harness));};mountFixture();
`;
const shared=manifest.scripts.filter(file=>file.startsWith('workbench/vendor/')||file.startsWith('workbench/assets/foundation-'));
const html='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">'+manifest.styles.map(file=>'<link rel="stylesheet" href="/static/'+file+'">').join('')+'<style>'+styles.map(row=>row.code).join('\n')+'</style></head><body class="aps-workbench"><main class="plana"><div id="root"></div></main>'+shared.map(file=>'<script src="/static/'+file+'"></script>').join('')+Array.from(scripts.keys(),file=>'<script src="'+file+'"></script>').join('')+'<script>'+fixture+'</script></body></html>';
const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}if(req.url==='/favicon.ico'){res.writeHead(204);res.end();return;}if(scripts.has(req.url)){res.setHeader('Content-Type','application/javascript');res.end(scripts.get(req.url));return;}const row=assets.get(req.url);if(row){res.setHeader('Content-Type',row.mime);res.end(fs.readFileSync(path.join(root,'static',row.path)));}else{res.writeHead(404);res.end();}});
const report={production_db:false,global_build:false,scope:'current parent and catalog components with revision-checking mock adapter',cases:[],errors:[],sources:sources.concat(styles).map(row=>({path:row.path,sha256:crypto.createHash('sha256').update(row.code).digest('hex')}))};
let page,browser;const button=name=>page.getByRole('button',{name,exact:true}),parent=()=>page.getByRole('dialog',{name:'编辑人员',exact:true});
async function run(name,action){await action();report.cases.push({name,passed:true});}
async function edit(){await button('编辑').click();await parent().waitFor();await parent().getByLabel('班次',{exact:true}).waitFor();}
async function save(){await parent().getByRole('button',{name:'保存',exact:true}).click();await page.getByText('保存已完成。',{exact:true}).waitFor();}
async function refresh(){await button('刷新最新资料').click();await page.getByText('最新资料已刷新。你修改的内容已保留，未修改的项已更新；下方显示当前已保存的资料。',{exact:true}).waitFor();assert.equal(await button('已核对，继续编辑').count(),0);}
async function rename(){await button('维护班次').click();await button('编辑 SHIFT1').click();const modal=page.getByRole('dialog',{name:'编辑班次档',exact:true});await modal.getByLabel('名称',{exact:true}).fill('两日班更新');await modal.getByRole('button',{name:'保存',exact:true}).click();await button('完成并返回').click();await parent().waitFor();await page.locator('.wb-resource-review').waitFor();}
(async()=>{try{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({executablePath:process.env.WORKBENCH_BROWSER,headless:true});report.browser=browser.version();page=await browser.newPage({viewport:{width:1392,height:924}});page.setDefaultTimeout(10000);page.on('pageerror',error=>report.errors.push(error.message));await page.goto('http://127.0.0.1:'+server.address().port);
 await run('manual-refresh-twice-keeps-edits-and-applies-new-context',async()=>{await edit();await parent().getByLabel('姓名',{exact:true}).fill('未保存的人员修改');await parent().getByLabel('班次',{exact:true}).selectOption('');
  await page.evaluate(()=>{fixture.person='服务器已改名称';fixture.status='leave';fixture.version++;});await parent().getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('alert').filter({hasText:'资料已变化'}).waitFor();
  await refresh();await refresh();assert.equal(await parent().getByLabel('姓名',{exact:true}).inputValue(),'未保存的人员修改');assert.equal(await parent().getByLabel('班次',{exact:true}).inputValue(),'');assert.equal(await parent().getByLabel('状态',{exact:true}).inputValue(),'leave');assert((await page.locator('.wb-resource-review').innerText()).includes('服务器已改名称'));await save();
  const state=await page.evaluate(()=>fixture);assert.equal(state.person,'未保存的人员修改');assert.equal(state.shiftRef,null);assert.equal(state.writes.length,2);assert.notEqual(state.writes[0].body.request_key,state.writes[1].body.request_key);});
 await page.evaluate(()=>mountFixture());await button('编辑').waitFor();
 await run('own-catalog-rename-refreshes-parent-and-retains-draft',async()=>{await edit();await parent().getByLabel('姓名',{exact:true}).fill('目录返回后的草稿');await rename();assert.equal(await parent().getByLabel('姓名',{exact:true}).inputValue(),'目录返回后的草稿');assert.equal(await parent().getByLabel('班次',{exact:true}).inputValue(),'2'.padStart(48,'0'));assert((await page.locator('.wb-resource-review').innerText()).includes('两日班更新'));await save();const state=await page.evaluate(()=>fixture);assert.equal(state.person,'目录返回后的草稿');assert.equal(state.shift,'两日班更新');assert.equal(state.writes.length,2);assert.equal(state.writes[1].body.input.relationships,undefined);});
 await page.evaluate(()=>mountFixture());await button('编辑').waitFor();
 await run('concurrent-change-after-catalog-refresh-still-rejects',async()=>{await edit();await parent().getByLabel('姓名',{exact:true}).fill('并发后保留的草稿');await rename();await page.evaluate(()=>{fixture.shift='真正并发修改';fixture.version++;});await parent().getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('alert').filter({hasText:'资料已变化'}).waitFor();assert.equal((await page.evaluate(()=>fixture)).person,'原人员');await refresh();assert.equal(await parent().getByLabel('姓名',{exact:true}).inputValue(),'并发后保留的草稿');await save();assert.equal((await page.evaluate(()=>fixture)).person,'并发后保留的草稿');});
 assert.deepEqual(report.errors,[]);report.completed=true;
 }catch(error){report.error=error.stack;process.exitCode=1;if(page)await page.screenshot({path:path.join(output,'FAILED.png')}).catch(()=>{});}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));fs.writeFileSync(path.join(output,'resource-context-refresh.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({output,cases:report.cases.length,error:report.error}));}})();
