'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const host = { window: {}, Date, Number, Map, Set, Object, Array, Math };
vm.createContext(host);
for (const file of ['WorkbenchFormat.js', 'PointContract.js', 'PointGanttModel.js', 'PlanSelectionModel.js', 'WorkbenchTerms.js', 'FieldContract.js', 'ActualGanttModel.js', 'ActualGanttWindow.js'])
  vm.runInContext(fs.readFileSync(path.resolve(__dirname, '../../frontend/workbench/app', file), 'utf8'), host);
const S = host.window.PlanSelectionModel, W = host.window.ActualGanttWindow, M = host.window.ActualGanttModel;
assert.equal(W.dimensions(1102).viewport, 810);
assert.equal(W.restoreLeft({ left: 50000, viewport: 1400 }, 810), 50000 * 810 / 1400, 'Resized restoration preserves time position, not old raw pixels');
assert.equal(W.restoreLeft({ left: 200 }, 810), 200, 'Legacy records without viewport retain their explicit pixel position');
const plan = { is_current_official: true, capabilities: { view: true }, plan_ref: 'explicit-plan' };
assert.equal(S.defaultPlan([plan]), plan);
assert.equal(S.defaultPlan([plan], 'requested-plan'), null);
for (const context of [{ plan_ref: 'historical' }, { query: 'B-1' }, { selected_task_ref: 'restored' }, { snapshot_ref: 'old' }])
  assert.equal(S.defaultPlan([plan], undefined, context), null, 'Any restored or explicit context suppresses default choice');
assert.equal(S.defaultPlan([{ ...plan, capabilities: { view: false } }]), null);
assert.equal(S.defaultPlan([plan, { ...plan, plan_ref: 'ambiguous' }]), null);
assert.equal(S.defaultPlan([]), null);
const data = { items: [{ task: { task_ref: 'task', start: '2026-01-01T08:00:00', end: '2026-01-01T16:00:00' },
  execution: { reports: [{ report_ref: 'report', actual_start: '2026-01-01T10:00:00', actual_end: '2026-01-01T11:00:00' }] } }] };
const model = { start: M.instant('2026-01-01T00:00:00'), end: M.instant('2026-09-12T12:00:00'), asOf: M.instant('2026-09-12T12:00:00') };
const before = JSON.stringify({ data, model }), initial = W.initial(data, model);
assert(initial.zoom > 100 && initial.zoom <= 1024, 'Remote as_of does not compress default plan window');
const span = (model.end - model.start) / initial.zoom, center = model.start + initial.center * (model.end - model.start);
const captured = W.capture({ left: 50000, top: 300 }, 1400, model, initial.zoom);
const advanced = { ...model, start: model.start - 3600000, end: model.end + 86400000 };
const restoredZoom = W.restoreZoom(captured, advanced, initial.zoom), restoredLeft = W.restoreLeft(captured, 810, advanced, restoredZoom);
const restoredWindow = W.capture({ left: restoredLeft, top: captured.top }, 810, advanced, restoredZoom);
assert(Math.abs(restoredWindow.centerAt - captured.centerAt) < .001, 'Changed axis and viewport retain the visible time center');
assert(Math.abs(restoredWindow.windowSpan - captured.windowSpan) < .001, 'Refresh retains the visible duration rather than the old scale ratio');
assert.equal(restoredWindow.top, 300);
assert.equal(W.restoreZoom({ left: 200 }, advanced, 4), 4, 'Legacy records retain their requested zoom');
assert.equal(W.restoreZoom({ windowSpan: 1 }, advanced, 1), 1024, 'Zoom remains bounded by the rendering contract');
assert(center - span / 2 <= M.instant(data.items[0].task.start));
assert(center + span / 2 >= M.instant(data.items[0].task.end));
assert.equal(W.anchor(data, model, 'task', 'report'), (M.instant('2026-01-01T10:30:00') - model.start) / (model.end - model.start));
assert.equal(W.anchor(data, model, 'task', null), (M.instant('2026-01-01T12:00:00') - model.start) / (model.end - model.start));
assert.equal(W.anchor(data, model, null, null), W.anchor(data, model, 'task', null));
const mark = { kind: 'actual', start: model.start, end: model.start + 1000, y: 14, height: 38 };
const box = W.markBox(mark, model, 800);
assert.equal(box.hitWidth, 4); assert.equal(box.hitLeft, 0, 'Axis edge retains full minimum hitbox');
assert(box.size > 0 && box.size < .001, 'Painted width retains its exact duration');
assert.equal(W.hitMark([mark], model, 800, 0, 3, 20), mark);
assert.equal(W.hitMark([mark], model, 800, 0, 4, 20), null);
assert.equal(W.hitMark([mark], model, 800, 0, 3, 60), null);
const neighbor = { ...mark, start: mark.end, end: mark.end + 1000 };
assert.equal(W.hitMark([mark, neighbor], model, 800, 0, box.size * 1.5, 20), neighbor, 'Overlapping minimum hitboxes choose the nearest real interval in DOM and canvas');
const point = { ...mark, kind: 'point', end: mark.start, height: 24 };
assert.equal(W.markBox(point, model, 800).size, 0); assert.equal(W.markBox(point, model, 800).hitWidth, 24);
assert.equal(JSON.stringify({ data, model }), before, 'Window and hit geometry never mutate DTO or axis');
assert.equal(model.asOf, M.instant('2026-09-12T12:00:00'));
console.log(JSON.stringify({ passed: true, contracts: ['default-current-context', 'plan-window', 'selected-anchor', 'four-pixel-hit', 'point-zero-duration', 'dto-axis-asof-preserved'] }));
require('./wbui_gantt_display_format.cjs');
