'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Module=require('node:module');
const ready=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const originalPath=path.join(__dirname,'final_execution_browser_support.cjs');
let source=fs.readFileSync(originalPath,'utf8');
const anchor='await chromium.launch({ executablePath: process.env.WORKBENCH_BROWSER, headless: true })';
assert.equal(source.split(anchor).length,2);
source=source.replace(anchor,"await require('./win7_workflow_transport.cjs').connect(chromium,ready.win7_evidence_root)");
source=source.replace("await p.theme('light');", "await p.theme('light');await page.bringToFront();await page.waitForFunction(()=>document.fonts.status==='loaded',null,{timeout:30000});");
fs.writeFileSync(path.join(ready.root,'executed-field-support.cjs'),source);
const executed=new Module(originalPath,module);executed.filename=originalPath;executed.paths=module.paths;
Module._cache[originalPath]=executed;executed._compile(source,originalPath);executed.loaded=true;
const filesPath=path.join(__dirname,'final_execution_field_files.cjs');
const filesSource=fs.readFileSync(filesPath,'utf8').replaceAll('tests.workbench.final_execution_fileedit','tests.workbench.win7_field_fileedit');
const filesModule=new Module(filesPath,module);filesModule.filename=filesPath;filesModule.paths=module.paths;
Module._cache[filesPath]=filesModule;filesModule._compile(filesSource,filesPath);filesModule.loaded=true;
const fieldPath=path.join(__dirname,'final_execution_field.cjs');
let fieldSource=fs.readFileSync(fieldPath,'utf8');
if(ready.resume_report&&process.argv[3]!=='restart'){
 const start=fieldSource.indexOf('  const initial = await readField();');
 const end=fieldSource.indexOf('  await files(p);');assert(start>0&&end>start);
 fieldSource=fieldSource.slice(0,start)+`  const prior=require('node:fs').readFileSync(ready.resume_report,'utf8');
  const previous=JSON.parse(prior);assert(previous.actions.slice(0,7).every(row=>row.passed));
  p.report.prior_completed={report:ready.resume_report,actions:previous.actions.filter(row=>row.passed)};
  p.report.created=previous.created;p.report.completed_task=previous.completed_task;
  await readField();
`+fieldSource.slice(end);
}
fs.writeFileSync(path.join(ready.root,'executed-field-probe.cjs'),fieldSource);
const fieldModule=new Module(fieldPath,module);fieldModule.filename=fieldPath;fieldModule.paths=module.paths;fieldModule._compile(fieldSource,fieldPath);
