from __future__ import annotations

from typing import Tuple

BLOCKED_PATH_RULES: Tuple[Tuple[str, str], ...] = (
    (".DS_Store", "macOS 自动生成文件，提交后只会制造无意义 diff"),
    ("*/.DS_Store", "macOS 自动生成文件，提交后只会制造无意义 diff"),
    (".iris/", "本机 Codex/Iris 临时计划文件，不属于项目源码"),
    (".playwright-mcp/", "本地浏览器调试产物，不属于项目源码"),
    (".limcode_", "LimCode 本地中间产物，不属于本次提交边界"),
    ("logs/aps_port.txt", "APS 本地运行时端口文件，换机器后无意义"),
    ("logs/aps_host.txt", "APS 本地运行时地址文件，换机器后无意义"),
    ("logs/aps_db_path.txt", "APS 本地运行时数据库路径，换机器后无意义"),
    ("logs/aps_runtime.json", "APS 本地运行时状态，换机器后无意义"),
    ("logs/aps_runtime.lock", "APS 本地运行锁文件，提交后会干扰别人"),
    ("logs/aps_secret_key.txt", "APS 本地密钥文件，不能提交"),
    ("launcher.log", "APS 本地启动日志可能包含本机路径或错误明细，不能提交"),
    ("*/launcher.log", "APS 本地启动日志可能包含本机路径或错误明细，不能提交"),
    ("evidence/QualityGate/quality_gate_manifest.json", "质量门禁 proof 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/current_full_test_debt.json", "质量门禁债务快照是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/full_test_debt_summary.json", "full-test-debt summary 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/full_test_debt_node_cache.json", "full-test-debt nodeid 缓存是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/architecture_scan_cache.json", "architecture scan 文件级缓存是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/startup_runtime_regressions.json", "startup regressions proof 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/required_regressions.json", "required regressions proof 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/required_regressions/", "required regressions 分组 proof 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/debt_ledger_sync.json", "debt ledger sync proof 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/ruff_check_full.json", "ruff full proof 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/pyright_gate_full.json", "pyright gate proof 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/pyright_tools_full.json", "pyright tools proof 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/quickref_vs_routes.md", "quickref/routes 对账报告是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/silent_fallback_inventory_acceptance/", "silent fallback 验收清单是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/receipts/", "质量门禁 receipts 是运行产物，应由当前门禁重新生成"),
    ("evidence/QualityGate/logs/", "质量门禁日志是运行产物，不应该混进普通提交"),
    ("evidence/QualityGate/long_gate/", "长耗时门禁缓存是本地运行产物，不应该混进普通提交"),
    ("evidence/QualityGate/collect_nodeids.json", "pytest collect nodeid 快照是运行产物，应由当前门禁重新生成"),
    ("evidence/FullSelfTest/pytest_tests_output.txt", "FullSelfTest 原始输出很重，应保留格式化报告而不是原始控制台输出"),
    ("aps_test.db", "本地测试数据库，不属于项目源码"),
    ("aps_test.db-", "本地测试数据库旁路文件，不属于项目源码"),
)

GENERIC_COMMIT_SUBJECTS = {
    "fix",
    "fix bug",
    "update",
    "change",
    "changes",
    "wip",
    "tmp",
    "temp",
    "debug",
    "修复",
    "更新",
    "修改",
    "提交",
    "改一下",
}
