"""Required regression coverage for the approved algorithm quality/efficiency work."""

ALGORITHM_EFFICIENCY_REQUIRED_TESTS = (
    "tests/algorithm/test_busy_union_closure.py",
    "tests/algorithm/test_gap_resource_quality.py",
    "tests/algorithm/test_graph_repair_deadline.py",
    "tests/algorithm/test_graph_repair_decisions.py",
    "tests/algorithm/test_graph_repair_multiround.py",
    "tests/algorithm/test_graph_repair_operation_neighbors.py",
    "tests/algorithm/test_graph_repair_real_decode.py",
    "tests/algorithm/test_native_snapshot_callback_boundaries.py",
    "tests/algorithm/test_optimizer_benchmark_timing_contract.py",
    "tests/algorithm/test_optimizer_budget_public_projection.py",
    "tests/algorithm/test_optimizer_comparison_baseline_lifecycle.py",
    "tests/algorithm/test_optimizer_deadline_boundary.py",
    "tests/algorithm/test_optimizer_end_to_end_matrix_contract.py",
    "tests/algorithm/test_optimizer_end_to_end_snapshot_contract.py",
    "tests/algorithm/test_optimizer_exact_oracle.py",
    "tests/algorithm/test_optimizer_multi_start_budget_integration.py",
    "tests/algorithm/test_optimizer_multi_start_decision_dedup.py",
    "tests/algorithm/test_optimizer_objective_aware_graph_features.py",
    "tests/algorithm/test_optimizer_quality_matrix_quality_contract.py",
    "tests/algorithm/test_optimizer_shared_budget.py",
    "tests/algorithm/test_owned_sgs_timeline.py",
    "tests/algorithm/test_resource_demand_contract.py",
    "tests/algorithm/test_resource_demand_neutral_comparison.py",
    "tests/algorithm/test_resource_demand_total_blocking.py",
    "tests/algorithm/test_sgs_native_score_reuse.py",
    "tests/algorithm/test_sgs_plain_auto_timelines.py",
    "tests/scheduler_graph/test_graph_preparation_efficiency.py",
    "tests/scheduler_graph/test_metrics_impact_components.py",
)
