from __future__ import annotations

MISC_REQUIRED_REGRESSION_GROUPS = (
    {
        "group_id": "scheduler_batches_material_resource",
        "label": "Scheduler batches, material, and resource contracts",
        "target_paths": (
            "tests/regression_scheduler_batches_degraded_visibility.py",
            "tests/regression_scheduler_batch_template_warning_surface.py",
            "tests/regression_scheduler_resource_dispatch_invalid_query_cleanup.py",
            "tests/regression_resource_dispatch_bad_time_rows_surface_degraded.py",
            "tests/regression_resource_dispatch_export_surfaces_degraded.py",
            "tests/regression_resource_dispatch_public_output_contract.py",
            "tests/regression_resource_dispatch_viewmodel_public_output_contract.py",
            "tests/regression_resource_dispatch_task_id_encoding.py",
            "tests/regression_resource_dispatch_overdue_summary_formats.py",
            "tests/regression_resource_dispatch_partial_overdue_summary_surfaces_warning.py",
            "tests/regression_resource_dispatch_invalid_summary_surfaces_overdue_degraded.py",
            "tests/regression_scheduler_excel_batches_preview_baseline_precision.py",
        ),
        "input_file_scopes": (
            "web/routes/domains/scheduler/scheduler_batches.py",
            "web/routes/domains/scheduler/scheduler_batch_detail.py",
            "web/routes/domains/scheduler/scheduler_excel_batches*.py",
            "web/routes/domains/scheduler/scheduler_resource_dispatch.py",
            "web/routes/domains/scheduler/scheduler_resource_dispatch_query.py",
            "web/routes/material.py",
            "web/routes/scheduler_batches.py",
            "web/routes/scheduler_batch_detail.py",
            "web/routes/scheduler_excel_batches.py",
            "web/routes/scheduler.py",
            "core/services/scheduler/**/*.py",
            "data/**/*.py",
            "templates/**/*.html",
            "static/**/*",
            "templates_excel/**/*",
            "app.py",
            "app_new_ui.py",
            "config.py",
            "schema.sql",
        ),
        "env_keys": (
            "APS_ENV",
            "APS_DB_PATH",
            "APS_EXCEL_TEMPLATE_DIR",
            "SECRET_KEY",
        ),
    },
    {
        "group_id": "request_services_runtime_error_boundary",
        "label": "Request services, runtime, and error boundary contracts",
        "target_paths": (
            "tests/regression_request_services_contract.py",
            "tests/regression_request_services_lazy_construction.py",
            "tests/regression_request_services_failure_propagation.py",
            "tests/regression_factory_request_lifecycle_observability.py",
            "tests/regression_system_request_services_contract.py",
            "tests/regression_maintenance_window_mutex.py",
            "tests/regression_database_high_version_failfast.py",
            "tests/regression_migration_schema_contract.py",
            "tests/regression_migrations.py",
            "tests/regression_operation_execution_migration_v16_contract.py",
            "tests/regression_operation_execution_migration_v18_contract.py",
            "tests/regression_operation_execution_migration_v19_contract.py",
            "tests/regression_error_field_label_source.py",
            "tests/regression_scheduler_data_route_error_contract.py",
            "tests/test_ui_mode.py",
            "tests/regression_safe_next_url_hardening.py",
            "tests/regression_safe_next_url_observability.py",
            "tests/regression_error_boundary_contract.py",
        ),
        "input_file_scopes": (
            "web/bootstrap/**/*.py",
            "web/error_boundary.py",
            "web/error_handlers.py",
            "web/ui_mode.py",
            "web/ui_mode_request.py",
            "web/ui_mode_store.py",
            "web/render_bridge.py",
            "web/manual_src_security.py",
            "web/routes/**/*.py",
            "web/bootstrap/*.py",
            "web/routes/__init__.py",
            "web/routes/navigation_utils.py",
            "web/routes/normalizers.py",
            "web/routes/system_utils.py",
            "web/routes/system_backup.py",
            "web/routes/system_history.py",
            "web/routes/system_logs.py",
            "web/routes/system_plugins.py",
            "web/routes/system_ui_mode.py",
            "web/routes/domains/scheduler/scheduler_config.py",
            "web/routes/domains/scheduler/scheduler_batches.py",
            "core/**/*.py",
            "data/**/*.py",
            "tests/operation_execution_migration_support.py",
            "plugins/**/*.py",
            "templates/**/*.html",
            "static/**/*",
            "app.py",
            "app_new_ui.py",
            "config.py",
            "schema.sql",
        ),
        "env_keys": (
            "APS_ENV",
            "APS_DB_PATH",
            "APS_LOG_DIR",
            "APS_BACKUP_DIR",
            "APS_EXCEL_TEMPLATE_DIR",
            "APS_CHROME_PATH",
            "SECRET_KEY",
            "chrome_executable_resolution",
            "chrome_version",
            "chrome_executable_identity",
        ),
    },
    {
        "group_id": "frontend_manual_excel",
        "label": "Frontend manual and Excel contracts",
        "target_paths": (
            "tests/test_excel_import_hardening.py",
            "tests/test_excel_utils_compare_digest_guard.py",
            "tests/regression_excel_conversion_output_contracts.py",
            "tests/regression_excel_hidden_payload_contract.py",
            "tests/regression_frontend_offline_static_assets.py",
            "tests/regression_mirror_template_sync.py",
            "tests/test_excel_renamed_column_conflicts.py",
            "tests/regression_import_execution_stats_source_row_num.py",
        ),
        "input_file_scopes": (
            "templates_excel/**/*",
            "docs/**/*.md",
            "static/docs/**/*.md",
            "web_new_test/static/docs/**/*.md",
            "templates/**/*.html",
            "web_new_test/templates/**/*.html",
            "static/**/*",
            "web_new_test/static/**/*",
            "web/routes/excel_*.py",
            "web/routes/process_excel_*.py",
            "web/routes/personnel_excel_*.py",
            "web/routes/equipment_excel_*.py",
            "web/routes/domains/scheduler/scheduler_excel*.py",
            "web/routes/domains/scheduler/scheduler_config_display_state.py",
            "web/routes/scheduler_excel*.py",
            "web/manual_src_security.py",
            "web/render_bridge.py",
            "web/viewmodels/**/*.py",
            "core/**/*.py",
            "data/**/*.py",
            "app.py",
            "app_new_ui.py",
            "config.py",
            "schema.sql",
        ),
        "env_keys": (
            "APS_ENV",
            "APS_DB_PATH",
            "APS_EXCEL_TEMPLATE_DIR",
            "APS_CHROME_PATH",
            "APS_STATIC_VERSION",
            "node_executable_realpath",
            "node_version",
            "chrome_executable_resolution",
            "chrome_version",
            "chrome_executable_identity",
        ),
    },
    {
        "group_id": "ui_layout_presenters_system",
        "label": "UI layout, presenters, and system contracts",
        "target_paths": (
            "tests/regression_system_history_route_contract.py",
            "tests/test_ui_browser_geometry_env.py",
            "tests/test_ui_geometry_html_contract.py",
            "tests/test_scan_py38plus_syntax.py",
            "tests/test_architecture_fitness.py",
            "tests/regression_ui_layout_risk_contract.py",
            "tests/regression_workbench_nav_entry_contract.py",
            "tests/regression_responsive_min_width_contract.py",
            "tests/regression_table_layout_readability_contract.py",
        ),
        "input_file_scopes": (
            "tests/ui_geometry_contract_data.py",
            "tests/ui_geometry_runtime_support.py",
            "tests/ui_geometry_browser_support.py",
            "tests/ui_geometry_probe.mjs",
            "tests/ui_geometry_cdp_client.mjs",
            "tests/ui_geometry_probe_page_eval.mjs",
            "templates/**/*.html",
            "web_new_test/templates/**/*.html",
            "static/**/*",
            "web_new_test/static/**/*",
            "web/viewmodels/**/*.py",
            "web/routes/system_*.py",
            "web/routes/system_backup.py",
            "web/routes/system_history.py",
            "web/routes/system_logs.py",
            "web/routes/system.py",
            "web/routes/system_bp.py",
            "web/routes/system_health.py",
            "web/routes/system_plugins.py",
            "web/routes/system_ui_mode.py",
            "web/routes/excel_utils.py",
            "web/routes/process_parts.py",
            "web/routes/process_excel_routes.py",
            "web/routes/domains/scheduler/scheduler_run.py",
            "web/routes/domains/scheduler/scheduler_batches.py",
            "web/routes/domains/scheduler/scheduler_batch_detail.py",
            "web/routes/domains/scheduler/scheduler_excel_batches.py",
            "web/routes/domains/scheduler/scheduler_week_plan.py",
            "core/**/*.py",
            "data/**/*.py",
            "app.py",
            "app_new_ui.py",
            "config.py",
            "schema.sql",
        ),
        "env_keys": (
            "APS_BROWSER_SMOKE_REQUIRED",
            "APS_CHROME_PATH",
            "APS_STATIC_VERSION",
            "CI",
            "chrome_executable_resolution",
            "chrome_version",
            "chrome_executable_identity",
            "chrome_headless_preflight",
            "node_executable_realpath",
            "node_version",
            "node_browser_runtime_capability",
            "NODE_OPTIONS",
        ),
    },
)
