"""Fixed workbench targets; registration is not a release or execution receipt.

Only REQUIRED groups join the existing must-pass registry. SUPPLEMENTAL groups
use the same scope schema for explicit selection, but do not change default gate
commands, skip allowances, or full_test_debt_shards' perf/serial classification.
"""

from __future__ import annotations

_SHARED_INPUT_SCOPES = (
    "core/infrastructure/**/*.py",
    "core/shared/**/*.py",
    "core/models/workbench_identity.py",
    "core/models/workbench_command.py",
    "core/services/workbench/commands.py",
    "data/repositories/base_repo.py",
    "data/repositories/workbench_identity_repo.py",
    "data/repositories/workbench_command_repo.py",
    "web/bootstrap/**/*.py",
    "web/public_token_registry.py",
    "web/routes/workbench/__init__.py",
    "web/routes/workbench/registration.py",
    "web/routes/workbench/api_responses.py",
    "web/routes/workbench/read_context.py",
    "web/routes/workbench/write_context.py",
    "tests/workbench/*_support.py",
    "tests/workbench/fixtures/*",
    "app.py",
    "app_new_ui.py",
    "config.py",
    "schema.sql",
)
_ENV_KEYS = (
    "APS_ENV", "APS_DB_PATH", "APS_LOG_DIR", "APS_BACKUP_DIR",
    "APS_EXCEL_TEMPLATE_DIR", "SECRET_KEY", "WORKBENCH_NODE", "NODE_PATH",
    "node_executable_realpath", "node_version",
)
_PLAN_READ_SCOPES = (
    "core/services/common/plan_identity.py",
    "core/services/common/plan_query.py",
    "core/services/common/bounded_plan_query.py",
)
_RUN_SCOPES = (
    *_PLAN_READ_SCOPES,
    "core/models/workbench_run*.py", "core/services/workbench/run_*.py",
    "core/services/workbench/preflight*.py", "core/services/workbench/execution_ledger*.py",
    "core/services/execution/**/*.py",
    "core/algorithm*/**/*.py", "core/services/scheduler/**/*.py",
    "data/repositories/*.py", "web/routes/workbench/scheduling_jobs.py",
    "web/routes/workbench/preflight.py", "web/routes/workbench/run_*.py",
    "core/services/workbench/official_plan_persistence.py",
)
_TRIAL_SCOPES = (
    *_RUN_SCOPES,
    "core/models/workbench_trial*.py", "core/services/workbench/trial*.py",
    "web/routes/workbench/trial*.py", "frontend/workbench/app/Trial*",
)
_POINT_PIECE_SCOPES = (
    *_TRIAL_SCOPES,
    "core/errors.py",
    "core/models/*.py",
    "core/services/workbench/zero_duration*.py",
    "core/services/workbench/piece_adoption*.py",
    "core/services/workbench/plan*.py",
    "core/services/workbench/point_plan_query.py",
    "core/services/workbench/production_report*.py",
    "core/services/workbench/template_lineage*.py",
    "core/services/scheduler/template_lineage*.py",
    "core/algorithm_contracts/schedule_point_evidence.py",
    "core/infrastructure/migrations/v31.py",
    "web/routes/workbench/materials.py",
    "tests/workbench/ea_zero_duration_support.py",
    "tests/workbench/piece_adoption_support.py",
    "tests/workbench/piece_chain_support.py",
    "core/algorithm_runtime/piece_input.py",
)
_LINEAGE_SCOPES = (
    "core/models/workbench_template_lineage.py",
    "core/infrastructure/workbench_template_lineage_schema.py",
    "core/infrastructure/workbench_lineage_lookup_schema.py",
    "core/infrastructure/migrations/v28.py",
    "core/services/workbench/template_lineage*.py",
    "core/services/scheduler/template_lineage*.py",
    "core/services/workbench/calibration*.py", "core/services/workbench/batch*.py",
    "core/services/scheduler/batch*.py", "data/repositories/*.py",
    "web/routes/workbench/batch*.py", "web/routes/workbench/calibration.py",
)
_DASHBOARD_SCOPES = (
    *_PLAN_READ_SCOPES,
    "core/models/workbench_dashboard*.py", "core/services/workbench/dashboard*.py",
    "core/services/workbench/plan*.py", "core/services/workbench/run_*.py",
    "core/services/workbench/execution_ledger*.py",
    "core/services/execution/**/*.py",
    "core/services/workbench/production_report*.py",
    "core/services/workbench/resource*.py", "core/services/workbench/preflight*.py",
    "core/services/workbench/batch*.py", "core/services/workbench/material*.py",
    "core/services/scheduler/**/*.py", "core/services/equipment/**/*.py",
    "data/repositories/*.py", "web/routes/workbench/dashboard.py",
    "frontend/workbench/app/Dashboard*",
    "core/infrastructure/workbench_outsourcing_schema.py",
    "core/models/workbench_outsourcing.py", "core/models/workbench_outsourcing_input.py",
    "core/services/workbench/dashboard_external.py", "core/services/workbench/dashboard_external_sources.py",
    "core/services/workbench/outsourcing.py", "core/services/workbench/outsourcing_projection.py",
    "data/repositories/workbench_outsourcing_repo.py", "data/repositories/workbench_outsourcing_source_repo.py",
    "web/routes/workbench/outsourcing.py", "tests/workbench/dashboard_external_support.py",
    "core/infrastructure/workbench_dashboard_external_schema.py",
    "data/repositories/workbench_dashboard_external_repo.py",
    "tests/workbench/dashboard_external_handling_support.py",
    "tests/workbench/dashboard_external_migration_support.py",
)


_SQLITE_SNAPSHOT_GROUPS = frozenset((
    "workbench_foundation", "workbench_resources", "workbench_process", "workbench_batches",
    "workbench_plans", "workbench_system", "workbench_field", "workbench_preflight",
    "workbench_mainmigration", "workbench_run_compute", "workbench_run_jobs", "workbench_trial",
    "workbench_template_lineage", "workbench_request_lifecycle", "workbench_calibration_adoption",
    "workbench_trial_adoption", "workbench_dashboard", "workbench_zero_duration", "workbench_piece_adoption",
    "workbench_browser", "workbench_browser_opt_in", "workbench_run_compute_capacity", "workbench_run_jobs_capacity",
    "workbench_run_history_capacity", "workbench_run_candidate_capacity", "workbench_run_baseline_capacity",
    "workbench_run_adoption_capacity", "workbench_identity_diagnostics", "workbench_trial_capacity",
))


def _group(group_id, label, filenames, scopes, env_keys=()):
    # Explicit filenames only: even test_*_support.py files are not pytest targets.
    snapshot = ("tests/_support/sqlite_snapshot.py",) if group_id in _SQLITE_SNAPSHOT_GROUPS else ()
    return {
        "group_id": group_id,
        "label": label,
        "target_paths": tuple("tests/workbench/" + name for name in filenames),
        "input_file_scopes": (*_SHARED_INPUT_SCOPES, *scopes, *snapshot),
        "env_keys": (*_ENV_KEYS, *env_keys),
    }


WORKBENCH_REQUIRED_REGRESSION_GROUPS = (
    {
        "group_id": "workbench_registry",
        "label": "Workbench registry and changed-source selection contracts",
        "target_paths": (
            "tests/gate_meta/test_workbench_registry_contract.py",
            "tests/gate_meta/test_workbench_cache_environment.py",
            "tests/workbench/test_fe04_shared_service_dependency_contract.py",
            "tests/gate_meta/test_workbench_round1_registry_contract.py",
            "tests/workbench/test_round1_execution_dependency_contract.py",
            "tests/workbench/test_round1_plan_query_dependency_contract.py",
        ),
        "input_file_scopes": (
            "tools/test_registry*.py",
            "tools/quality_gate_shared.py",
            "tools/long_gate_manifest.py",
            "tools/long_gate_manifest_environment.py",
            "tools/long_gate_fingerprint.py",
            "tools/long_gate_cache.py",
            "tools/long_gate_schema.py",
            "tests/gate_meta/workbench_cache_environment_support.py",
            "tools/full_test_debt_shards.py",
            "tools/verify_required_regressions_from_full_test_debt.py",
            "scripts/run_daily_quality_gate.py",
            "tests/workbench/*.py",
            "tests/algorithm/test_busy_block_native_equivalence.py",
            "tests/algorithm/test_busy_block_boundaries.py",
            "tests/_support/busy_block_case.py",
            # FE-04 invokes the real import scanner and scans test consumers too.
            "core/**/*.py", "web/**/*.py", "data/**/*.py", "desktop/**/*.py",
            "plugins/**/*.py", "tools/**/*.py", "scripts/**/*.py", "*.py", "tests/**/*.py",
        ),
    },
    _group("workbench_foundation", "Workbench entry, identity and request contracts", (
        "test_entry.py",
        "test_identity_metadata.py",
        "test_identity_replacements.py",
        "test_identity_key_codec.py",
        "test_commands.py",
        "test_read_context.py",
        "test_write_context.py",
        "test_foundation_dependency_scope.py",
        "test_transport.py",
        "test_theme.py",
    ), (
        "web/routes/workbench/assets.py", "web/routes/workbench/pages.py",
        "frontend/workbench/app/*.js", "templates/workbench/*.html",
        "scripts/workbench/*.py", "scripts/workbench/*.json",
    )),
    _group("workbench_resources", "Workbench resources, calendars and materials", (
        "test_resource_schema.py",
        "test_resource_entities.py",
        "test_resource_relations.py",
        "test_resource_catalogs.py",
        "test_resource_metrics.py",
        "test_resource_calendar_summary.py",
        "test_resource_api.py",
        "test_resource_table_queries.py",
        "test_resource_table_api.py",
        "test_resource_table_scale.py",
        "test_resource_transport.py",
        "test_resource_files.py",
        "test_resource_file_codec.py",
        "test_resource_file_api.py",
        "test_resource_file_scale.py",
        "test_resource_file_calendar_connection.py",
        "test_resource_bulk.py",
        "test_column_export_scope.py",
        "test_calendars.py",
        "test_calendar_api.py",
        "test_operator_qualification.py",
        "test_operator_shift_calendar.py",
        "test_suppliers.py",
        "test_supplier_capabilities.py",
        "test_material_queries.py",
        "test_material_query_scale.py",
        "test_material_commands.py",
        "test_material_api.py",
        "test_material_actions_api.py",
        "test_material_files.py",
        "test_material_bulk.py",
        "test_resource_table_domain_pairing.py",
        "test_fe01_resource_static_contract.py",
    ), (
        "core/models/workbench_resource*.py", "core/models/workbench_material*.py",
        "core/models/workbench_calendar.py", "core/models/workbench_supplier.py",
        "core/services/workbench/resource*.py", "core/services/workbench/material*.py",
        "core/services/workbench/calendars.py", "core/services/workbench/suppliers.py",
        "core/services/personnel/**/*.py", "core/services/equipment/**/*.py",
        "core/services/material/**/*.py", "core/services/process/**/*.py",
        "core/services/scheduler/operator_shift_calendar.py",
        "data/repositories/*.py",
        "web/routes/workbench/resource*.py", "web/routes/workbench/material*.py",
        "web/routes/workbench/calendars*.py",
        "frontend/workbench/app/Resource*", "frontend/workbench/app/Calendar*",
        "tests/workbench/resource*probe.cjs", "tests/workbench/material*probe.cjs",
    )),
    _group("workbench_process", "Workbench process stages, files and collection APIs", (
        "test_process_identity_schema.py",
        "test_process_identity_performance.py",
        "test_process_workflow_schema.py",
        "test_process_workflow_state.py",
        "test_process_queries.py",
        "test_process_read_api.py",
        "test_process_readiness.py",
        "test_process_table.py",
        "test_process_table_api.py",
        "test_process_part_actions.py",
        "test_process_collection_api.py",
        "test_process_collection_api_transactions.py",
        "test_process_route_preview.py",
        "test_process_route_confirm.py",
        "test_process_stage_commands.py",
        "test_process_stage_api.py",
        "test_process_batch_gate.py",
        "test_process_file_codec.py",
        "test_process_file_route.py",
        "test_process_file_route_apply.py",
        "test_process_file_hours_preview.py",
        "test_process_file_hours_apply.py",
        "test_process_file_hours_roundtrip.py",
        "test_process_file_hours_scale.py",
        "test_process_file_api_exports.py",
        "test_process_file_api_imports.py",
        "test_process_file_api_parameters.py",
        "test_process_file_api_transactions.py",
        "test_process_file_api_scale.py",
        "test_process_quota_protection.py",
        "test_process_quota_protection_excel.py",
        "test_process_quota_protection_routes.py",
        "test_process_quota_protection_transactions.py",
        "test_process_quota_protection_stage_regressions.py",
        "test_process_quota_protection_file_receipts.py",
        "test_process_quota_protection_file_receipt_failures.py",
        "test_merged_cycle_projection.py", "test_merged_cycle_projection_api.py",
        "test_eu_process_fixture_contracts.py",
        "test_round1_process_contract.py", "test_round1_process_boundaries.py",
    ), (
        "core/models/workbench_process*.py", "core/services/workbench/process*.py",
        "core/services/process/**/*.py", "core/services/workbench/batch*.py",
        "data/repositories/*.py", "web/routes/workbench/process*.py",
        "frontend/workbench/app/Process*", "tests/workbench/process*probe.cjs",
        "frontend/workbench/app/resource-contract.js",
        "frontend/workbench/prototype/ui_kits/workbench/assets/vendor/babel-7.29.0.min.js",
        "core/models/workbench_master_overview.py", "core/services/workbench/master_overview*.py",
        "core/services/workbench/resource_readiness.py", "web/routes/process_parts.py",
    )),
    _group("workbench_batches", "Workbench batch commands, files and ledger guards", (
        "test_batch_commands.py",
        "test_batch_actions.py",
        "test_batch_files.py",
        "test_batch_execution_ledger_projection.py",
        "test_batch_execution_ledger_guards.py",
        "test_batch_execution_ledger_atomic.py",
        "test_batch_execution_ledger_boundaries.py",
        "test_batch_round1_boundaries.py",
    ), (
        "core/models/workbench_batch*.py", "core/services/workbench/batch*.py",
        "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/production_report*.py",
        "core/services/scheduler/batch*.py", "data/repositories/*.py",
        "web/routes/workbench/batch*.py", "frontend/workbench/app/Batch*",
        "core/services/workbench/template_lineage*.py",
        "core/services/scheduler/template_lineage*.py",
        "tests/workbench/test_batch_files.py",
    )),
    _group("workbench_plans", "Workbench plan identity, query, calendar and delivery", (
        "test_plan_baseline.py",
        "test_plan_catalog.py",
        "test_plan_calendar.py",
        "test_plan_calendar_runtime_dates.py",
        "test_plan_delivery.py",
        "test_plan_delivery_scale.py",
        "test_plan_occupancy.py",
        "test_plan_page.py",
        "test_plan_persistent_identity.py",
        "test_plan_public_projection.py",
        "test_plan_runtime_dates.py",
        "test_plan_workspace_projections.py",
        "test_plan_query_api.py",
        "test_plan_export_api.py",
        "test_plan_transport.py",
        "test_official_plan_persistence.py",
        "test_plan_adoption_baseline.py",
        "test_plan_adoption_baseline_api.py",
        "test_plan_adoption_baseline_integrity.py",
        "test_round1_plan_contract_boundaries.py", "test_round1_plan_contract_projections.py",
    ), (
        "core/models/workbench_plan*.py", "core/services/workbench/plan*.py",
        *_PLAN_READ_SCOPES,
        "core/services/scheduler/**/*.py", "data/repositories/*.py",
        "web/routes/workbench/plan*.py", "frontend/workbench/app/Plan*",
        "tests/workbench/plan*probe.cjs",
        "core/services/workbench/official_plan_persistence.py",
        "core/services/workbench/run_candidate_adoption_storage.py",
        "core/services/workbench/run_candidate_baseline.py",
        "core/services/workbench/run_candidate_facts.py",
        "core/services/workbench/run_candidate_storage.py",
        "core/services/workbench/trial_adoption_storage.py",
        "core/models/workbench_trial_codec.py",
        "core/models/workbench_run_adoption.py",
        "core/services/workbench/run_candidate_adoption.py",
    )),
    _group("workbench_reports", "Workbench reports, exports and execution ledger views", (
        "test_report_read.py",
        "test_report_export.py",
        "test_report_boundaries.py",
        "test_report_execution_ledger_read.py",
        "test_report_execution_ledger_identity.py",
        "test_report_execution_ledger_export.py",
        "test_report_execution_ledger_boundaries.py",
        "test_report_execution_ledger_scale.py",
        "test_round1_analytics_contract.py", "test_round1_report_export_contract.py",
    ), (
        "core/models/workbench_report*.py", "core/services/workbench/report*.py",
        *_PLAN_READ_SCOPES,
        "core/services/workbench/review*.py", "core/services/workbench/plan*.py",
        "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/production_report*.py",
        "core/services/report/**/*.py", "data/repositories/*.py",
        "web/routes/workbench/report*.py", "frontend/workbench/app/Report*",
        "tests/workbench/report*probe.cjs",
    )),
    _group("workbench_system", "Workbench system maintenance and master overview APIs", (
        "test_system_maintenance_api.py",
        "test_system_maintenance_restore.py",
        "test_system_maintenance_failures.py",
        "test_master_overview_reads.py",
        "test_master_overview_boundaries.py",
        "test_system_restore_host.py",
        "test_system_restore_host_drain.py",
        "test_system_restore_host_recovery.py",
        "test_system_restore_entrypoint.py",
        "test_system_restore_entrypoint_fail_closed.py",
        "test_system_restore_entrypoint_recovery.py",
        "test_du_system_restore_view.py",
        "test_round1_host_boundaries.py",
        "test_round1_runtime_observation.py",
    ), (
        "core/models/workbench_system.py", "core/models/workbench_master_overview.py",
        "core/models/operation_log_labels.py",
        "core/services/system/**/*.py", "core/services/workbench/system*.py",
        "core/services/system/backup_restore.py", "web/routes/system_backup_actions.py",
        "core/services/process/unit_excel/**/*.py", "core/services/process/unit_excel_converter.py",
        "core/services/workbench/master_overview*.py",
        "core/services/workbench/resource*.py", "core/services/workbench/process*.py",
        "core/services/workbench/material*.py", "core/services/workbench/calendars.py",
        "data/repositories/*.py", "web/routes/workbench/system*.py",
        "web/routes/workbench/master_overview.py",
        "frontend/workbench/app/System*", "frontend/workbench/app/MasterOverview*",
        "web/bootstrap/entrypoint.py", "web/bootstrap/launcher_shutdown.py",
        "web/bootstrap/launcher_stop.py", "web/bootstrap/workbench_system_restore_status.py",
        "tests/workbench/system_restore_entrypoint_support.py",
        "tests/workbench/system_restore_entrypoint_process_support.py",
        "tests/workbench/system_restore_entrypoint_legacy_support.py",
        "web/bootstrap/workbench_system_restore_view.py",
        "templates/workbench/recovery.html",
        "tests/workbench/system_restore_host_support.py",
    )),
    _group("workbench_execution_ledger", "Execution ledger: eight domain contract files", (
        "test_execution_ledger.py",
        "test_execution_ledger_contracts.py",
        "test_execution_ledger_commands.py",
        "test_execution_ledger_constraints.py",
        "test_execution_ledger_legacy.py",
        "test_execution_ledger_scope.py",
        "test_execution_ledger_source_integrity.py",
        "test_execution_ledger_scale.py",
        "test_round1_execution_contract.py",
    ), (
        "core/models/workbench_execution*.py",
        "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/production_report*.py",
        "core/services/scheduler/execution*.py", "core/services/scheduler/execution/**/*.py",
        "data/repositories/workbench_execution*.py",
        "data/repositories/workbench_plan_identity_repo.py",
        "web/routes/workbench/execution*.py",
        *_PLAN_READ_SCOPES,
    )),
    _group("workbench_execution_scheduler", "Execution ledger scheduler input and persistence guards", (
        "test_scheduler_execution_ledger.py",
        "test_scheduler_execution_ledger_guards.py",
        "test_scheduler_execution_ledger_snapshot.py",
        "test_scheduler_execution_ledger_scale.py",
    ), (
        "core/models/workbench_execution*.py", "core/services/scheduler/**/*.py",
        *_PLAN_READ_SCOPES,
        "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/production_report*.py", "data/repositories/*.py",
    )),
    _group("workbench_field", "Field workspace, report files and actual Gantt API", (
        "test_field_workspace_api.py",
        "test_field_files_api.py",
        "test_field_files_codec.py",
        "test_actual_gantt_api.py",
        "test_point_downstream_api.py",
        "test_round1_field_piece_files.py", "test_round1_field_piece_files_codec.py",
        "test_round1_field_piece_files_contract.py",
    ), (
        *_POINT_PIECE_SCOPES,
        "core/models/workbench_execution*.py", "core/services/workbench/field*.py",
        "core/services/workbench/actual_gantt*.py", "core/services/workbench/plan*.py",
        "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/production_report*.py", "data/repositories/*.py",
        "web/routes/workbench/execution*.py", "web/routes/workbench/actual_gantt.py",
        "frontend/workbench/app/Field*", "frontend/workbench/app/ActualGantt*",
        "core/services/workbench/report*.py", "web/routes/workbench/reports.py",
        "tests/workbench/point_downstream_support.py",
    )),
    _group("workbench_preflight", "Readonly preflight APIs, ledger facts and query budgets", (
        "test_preflight_api.py",
        "test_preflight_ledger.py",
        "test_preflight_capacity.py",
        "test_preflight_run_status.py",
    ), (
        *_RUN_SCOPES,
        "core/models/workbench_preflight.py", "core/services/workbench/preflight*.py",
        "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/production_report*.py", "data/repositories/*.py",
        "core/services/scheduler/**/*.py", "web/routes/workbench/preflight.py",
        "frontend/workbench/app/Preflight*",
        "core/services/workbench/preflight_result.py", "core/services/workbench/run_jobs.py",
        "tests/workbench/preflight_support.py", "tests/workbench/request_lifecycle_support.py",
        "web/bootstrap/factory.py", "web/bootstrap/launcher_runtime_lock.py",
        "web/bootstrap/workbench_request_lifecycle.py", "web/bootstrap/workbench_run_runtime.py",
    )),
    _group("workbench_mainmigration", "Real startup migrations and registered cross-domain APIs", (
        "test_execution_ledger_migration.py",
        "test_run_schema_migration.py",
        "test_plan_migration_integration.py",
        "test_migration_pages_fixture.py",
        "test_trial_lineage_migration.py",
        "test_lineage_lookup_migration.py",
        "test_calibration_dashboard_migration.py",
        "test_outsourcing_identity_migration.py",
        "test_dashboard_external_migration.py",
    ), (
        "core/infrastructure/migrations/v25.py",
        "core/infrastructure/migrations/v26.py",
        "core/infrastructure/migrations/v27.py",
        "core/infrastructure/migrations/v28.py",
        "core/infrastructure/migrations/v29.py",
        "core/infrastructure/migrations/v30.py",
        "core/infrastructure/migrations/v31.py",
        "core/infrastructure/workbench_dashboard_external_schema.py",
        "core/infrastructure/workbench_outsourcing_schema.py",
        "core/infrastructure/workbench_plan_identity_write_guard.py",
        "core/infrastructure/workbench_run_schema.py",
        "core/infrastructure/workbench_trial_schema.py",
        "core/infrastructure/workbench_template_lineage_schema.py",
        "core/infrastructure/workbench_lineage_lookup_schema.py",
        "core/infrastructure/workbench_calibration_adoption_schema.py",
        "core/infrastructure/workbench_dashboard_schema.py",
        "core/services/workbench/**/*.py", "core/models/workbench*.py",
        *_PLAN_READ_SCOPES,
        "core/services/execution/**/*.py",
        "data/repositories/*.py", "web/routes/workbench/**/*.py",
        "tests/workbench/execution_ledger_migration_support.py",
        "tests/workbench/run_schema_migration_support.py",
        "tests/workbench/migration_pages_live_server.py",
        "tests/workbench/fixtures/schema-v24.sql",
        "tests/workbench/fixtures/schema-v25.sql",
        "tests/workbench/fixtures/schema-v26.sql",
        "tests/workbench/fixtures/schema-v27.sql",
        "tests/workbench/fixtures/schema-v28.sql",
        "tests/workbench/fixtures/schema-v29.sql",
        "tests/workbench/fixtures/schema-v30.sql",
        "tests/workbench/trial_lineage_migration_support.py",
        "tests/workbench/calibration_dashboard_migration_support.py",
        "tests/workbench/outsourcing_identity_migration_support.py",
        "tests/workbench/dashboard_external_migration_support.py",
    )),
    # These are isolated component contracts, not a claim of global run integration.
    _group("workbench_run_compute", "Unreleased candidate-compute component contracts", (
        "test_run_snapshot_reuse.py",
        "test_run_compute.py",
        "test_run_compute_contracts.py",
        "test_run_compute_execution.py",
        "test_run_compute_integration.py",
        "test_run_compute_readonly.py",
        "test_round1_run_boundaries_input.py", "test_round1_run_boundaries_compute.py",
    ), (
        "core/models/workbench_run_compute.py", "core/services/workbench/run_compute*.py",
        *_PLAN_READ_SCOPES,
        "core/services/workbench/run_input*.py", "core/algorithm*/**/*.py",
        "core/services/scheduler/**/*.py", "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/resource*.py", "data/repositories/*.py",
    )),
    _group("workbench_run_jobs", "Unreleased run-job admission, runtime, history and candidate API contracts", (
        "test_run_jobs.py",
        "test_run_jobs_schema.py",
        "test_run_jobs_api.py",
        "test_run_jobs_atomic.py",
        "test_run_jobs_concurrency.py",
        "test_run_jobs_recovery.py",
        "test_run_jobs_restart.py",
        "test_run_runtime.py",
        "test_run_runtime_lock.py",
        "test_run_runtime_recovery.py",
        "test_run_runtime_lifecycle.py",
        "test_run_entrypoint.py",
        "test_run_history_queries.py",
        "test_run_history_snapshots.py",
        "test_run_history_integrity.py",
        "test_run_history_api.py",
        "test_run_candidate_queries.py",
        "test_run_candidate_boundaries.py",
        "test_run_candidate_exports.py",
        "test_run_candidate_api.py",
        "test_run_candidate_baseline_api.py",
        "test_run_candidate_baseline_queries.py",
        "test_run_candidate_baseline_integrity.py",
        "test_run_candidate_adoption.py", "test_run_candidate_adoption_resources.py",
        "test_run_candidate_adoption_atomic.py", "test_run_candidate_adoption_boundaries.py",
        "test_run_candidate_adoption_api.py",
        "test_run_adoption_host.py",
        "test_round1_run_boundaries_models.py", "test_round1_run_boundaries_candidates.py",
        "test_final_planning_analysis.py", "test_final_planning_analysis_history.py",
        "test_final_planning_analysis_contract.py",
    ), (
        "core/models/workbench_run*.py", "core/services/workbench/run_*.py",
        *_PLAN_READ_SCOPES,
        "core/services/workbench/preflight*.py", "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/scheduler/**/*.py", "data/repositories/*.py",
        "web/routes/workbench/scheduling_jobs.py", "web/routes/workbench/preflight.py",
        "core/algorithm*/**/*.py", "web/routes/workbench/run_*.py",
        "core/services/workbench/official_plan_persistence.py",
        "tests/workbench/final_planning_analysis_contract.cjs",
        "frontend/workbench/app/RunCandidateAPI.js",
        "frontend/workbench/app/RunCandidateAnalysisAPI.js",
    )),
    _group("workbench_calibration", "Readonly calibration provenance, method and exports", (
        "test_calibration_method.py", "test_calibration_integrity.py", "test_calibration_routes.py",
    ), (
        "core/models/workbench_calibration.py", "core/services/workbench/calibration*.py",
        "core/services/workbench/execution_ledger*.py", "core/services/workbench/production_report*.py",
        "core/services/execution/**/*.py",
        "data/repositories/workbench_calibration*.py", "web/routes/workbench/calibration.py",
        "tests/workbench/calibration_support.py",
        "frontend/workbench/app/Calibration*",
        "core/services/workbench/template_lineage*.py",
        "core/services/scheduler/template_lineage*.py",
    )),
    _group("workbench_trial", "Trial drafts, validation, atomic writes and catalog APIs", (
        "test_trial_lifecycle.py", "test_trial_validation.py", "test_trial_atomic.py",
        "test_trial_api_schema.py", "test_trial_edges.py", "test_trial_catalog.py",
        "test_ep_trial_fixture_contracts.py",
        "test_trial_predecessor_labels.py",
        "test_fe02_trial_static_contract.py",
        "test_round1_trial_boundaries.py",
    ), (*_POINT_PIECE_SCOPES, "tests/workbench/run_baseline_widgets_support.py",
        "tests/workbench/trial_widgets_support.py",
        "tests/workbench/trial_predecessor_labels_probe.cjs",
        "frontend/workbench/app/PointContract.js", "frontend/workbench/app/ResourceControls.jsx",
        "frontend/workbench/app/TrialControls.jsx", "frontend/workbench/app/TrialGantt.jsx",
        "frontend/workbench/app/TrialDetails.jsx", "scripts/workbench/compile.cjs",
        "frontend/workbench/prototype/ui_kits/workbench/assets/vendor/babel-7.29.0.min.js",
        "frontend/workbench/prototype/ui_kits/workbench/assets/vendor/react-18.3.1.js")),
    _group("workbench_template_lineage", "Template origins, legacy copies and calibration integrity", (
        "test_template_lineage_schema.py", "test_template_lineage_writes.py",
        "test_template_lineage_integrity.py", "test_template_lineage_calibration.py",
        "test_legacy_batch_lineage_copy.py",
    ), _LINEAGE_SCOPES),
    _group("workbench_request_lifecycle", "HTTP request admission, draining and maintenance ownership", (
        "test_request_lifecycle_registration.py", "test_request_lifecycle_http.py",
        "test_request_lifecycle_errors.py", "test_request_lifecycle_maintenance.py",
        "test_request_lifecycle_runtime.py", "test_request_lifecycle_factory.py",
        "test_fe03_request_ticket_contract.py", "test_fe03_request_package_contract.py",
    ), (
        *_RUN_SCOPES,
        "web/bootstrap/workbench_request_lifecycle*.py",
        "web/bootstrap/__init__.py", "web/bootstrap/factory.py",
        "web/routes/workbench/**/*.py", "web/routes/workbench/pages.py",
        "tests/workbench/fe03_route_manifest.json",
        "core/services/system/maintenance/*.py",
        "core/services/system/system_maintenance_service.py",
        "core/services/workbench/system*.py",
    )),
    _group("workbench_calibration_adoption", "Calibration quota adoption, drift and atomic audit contracts", (
        "test_calibration_adoption.py", "test_calibration_adoption_schema.py",
        "test_calibration_adoption_drift.py", "test_calibration_adoption_transactions.py",
        "test_calibration_adoption_routes.py",
        "test_calibration_adoption_host.py",
    ), (
        *_LINEAGE_SCOPES,
        "core/models/workbench_calibration_adoption.py",
        "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/production_report*.py",
        "core/services/workbench/process*.py", "core/services/process/**/*.py",
        "web/routes/workbench/calibration_adoption.py",
        "frontend/workbench/app/Calibration*",
    )),
    _group("workbench_trial_adoption", "Saved trial adoption, exact scope, restart and raw preservation", (
        "test_trial_adoption.py", "test_trial_adoption_validation.py",
        "test_trial_adoption_boundaries.py", "test_trial_adoption_atomic.py",
        "test_trial_adoption_raw.py", "test_trial_adoption_restart.py",
        "test_trial_adoption_api.py", "test_trial_adoption_host.py",
        "test_trial_adoption_history.py", "test_trial_adoption_history_api.py",
        "test_trial_adoption_history_boundaries.py",
    ), (*_TRIAL_SCOPES, "core/services/workbench/plan_queries.py")),
    _group("workbench_dashboard", "Dashboard reads, commands, host connections and retained history", (
        "test_dashboard_schema.py", "test_dashboard_reads.py", "test_dashboard_candidates.py",
        "test_dashboard_commands.py", "test_dashboard_atomic.py", "test_dashboard_api.py",
        "test_dashboard_host_connection.py", "test_dashboard_legacy.py",
        "test_dashboard_external_reads.py", "test_dashboard_external_identity.py", "test_dashboard_external_snapshot.py",
        "test_dashboard_external_handling_schema.py", "test_dashboard_external_handling_commands.py",
        "test_dashboard_external_handling_atomic.py", "test_dashboard_external_handling_identity.py",
        "test_dashboard_external_handling_api.py",
    ), _DASHBOARD_SCOPES),
    _group("workbench_outsourcing", "Explicit outsourcing facts, identity, SQL and API contracts", (
        "test_outsourcing_facts.py", "test_outsourcing_identity.py", "test_outsourcing_schema.py",
        "test_outsourcing_atomic.py", "test_outsourcing_api.py",
        "test_outsourcing_targets_labels.py",
        "test_round1_outsourcing_contract.py",
    ), (
        "core/models/workbench_outsourcing*.py", "core/services/workbench/outsourcing*.py",
        *_PLAN_READ_SCOPES,
        "core/services/workbench/plan*.py", "core/services/workbench/template_lineage*.py",
        "core/services/scheduler/template_lineage*.py",
        "core/services/workbench/execution_ledger*.py", "core/services/workbench/production_report*.py",
        "core/services/execution/**/*.py",
        "core/services/workbench/dashboard*.py", "web/routes/workbench/dashboard.py",
        "data/repositories/workbench_outsourcing*.py", "web/routes/workbench/outsourcing.py",
        "tests/workbench/outsourcing_support.py", "tests/workbench/outsourcing_targets_labels_support.py",
        "tests/workbench/fixtures/schema-v29.sql",
    )),
    # Backend integration evidence does not enable the public point-rendering surface.
    _group("workbench_zero_duration", "Point-event math, backend integration and live DTO contracts", (
        "test_zero_duration_contract.py", "test_zero_duration_calendar.py", "test_zero_duration_boundaries.py",
        "test_ea_zero_duration_chain.py", "test_ea_zero_duration_boundaries.py", "test_ea_zero_duration_constraints.py",
        "test_point_public_contract.py",
        "test_point_adoption_host.py",
    ), (*_POINT_PIECE_SCOPES, "tests/workbench/point_public_contract_probe.cjs",
        "frontend/workbench/app/PointContract.js", "frontend/workbench/app/RunCandidateAPI.js",
        "frontend/workbench/app/RunBaselineAPI.js", "tests/workbench/run_entrypoint_support.py",
        "tests/workbench/test_run_adoption_host.py", "tests/workbench/trial_adoption_support.py",
        "web/routes/workbench/actual_gantt.py", "web/routes/workbench/execution.py",
        "core/services/workbench/actual_gantt*.py", "core/services/workbench/field*.py")),
    # EC helper contracts and EF's delivered real-worker/DAG integration.
    _group("workbench_piece_adoption", "Piece scope, worker DAG, execution and retained adoption", (
        "test_piece_adoption.py", "test_piece_adoption_boundaries.py",
        "test_piece_adoption_execution.py", "test_piece_adoption_persistence.py",
        "test_piece_chain_input.py", "test_piece_chain_end_to_end.py",
        "test_piece_chain_execution.py", "test_piece_chain_external.py", "test_piece_chain_boundaries.py",
        "test_piece_presentation.py", "test_piece_production_connection.py",
        "test_round1_piece_point_chain.py", "test_round1_piece_point_constraints.py",
        "test_round1_piece_point_evidence.py", "test_round1_piece_point_protection.py",
    ), (*_POINT_PIECE_SCOPES,
        "tests/workbench/test_piece_chain_end_to_end.py",
        "tests/workbench/piece_production_connection_support.py",
        "core/infrastructure/database.py", "core/services/workbench/plan_projection.py",
        "core/services/workbench/run_candidate_facts.py", "core/services/workbench/run_candidate_tasks.py",
        "core/services/workbench/trial_adoption_validation.py",
    ), ("APS_ET_EVIDENCE_ROOT",)),
)

WORKBENCH_REQUIRED_TESTS = tuple(
    path for group in WORKBENCH_REQUIRED_REGRESSION_GROUPS for path in group["target_paths"]
)

# Explicit, non-required inventory. No implicit perf marking or skip-to-pass
# conversion: current full pytest still discovers these, daily required does not.
_BROWSER_SCOPES = (
    *_PLAN_READ_SCOPES,
    "core/services/workbench/**/*.py", "core/models/workbench*.py",
    "core/services/execution/**/*.py",
    "core/services/system/**/*.py", "core/services/scheduler/**/*.py",
    "data/repositories/*.py", "web/routes/workbench/**/*.py",
    "frontend/workbench/**/*", "static/workbench/**/*", "templates/workbench/**/*",
    "scripts/workbench/**/*", "tests/workbench/*.py", "tests/workbench/*.cjs",
    "tests/workbench/*.mjs", "tests/workbench/*.jsx",
)
_BROWSER_ENV_KEYS = ("WORKBENCH_BROWSER", "APS_CHROME_PATH", "NODE_OPTIONS")
_DASHBOARD_EXTERNAL_BROWSER_SCOPES = (
    "frontend/workbench/app/ResourceControls.jsx",
    "frontend/workbench/app/WorkbenchControlStyles.jsx",
    "frontend/workbench/app/WorkbenchControlBridge.js",
    "frontend/workbench/app/WorkbenchSelectMenu.jsx",
    "frontend/workbench/app/WorkbenchDatePickerModel.js",
    "frontend/workbench/app/WorkbenchDatePicker.jsx",
    "frontend/workbench/app/WorkbenchControls.jsx",
    "frontend/workbench/app/WorkbenchNumberControls.jsx",
    "frontend/workbench/app/OutsourcingContract.js",
    "frontend/workbench/app/OutsourcingSession.js",
    "frontend/workbench/app/OutsourcingControls.jsx",
    "frontend/workbench/app/OutsourcingStyles.jsx",
    "frontend/workbench/app/OutsourcingWorkspace.jsx",
    "frontend/workbench/app/DashboardContract.js",
    "frontend/workbench/app/DashboardSession.js",
    "frontend/workbench/app/DashboardStyles.jsx",
    "frontend/workbench/app/DashboardPanels.jsx",
    "frontend/workbench/app/DashboardHistory.jsx",
    "frontend/workbench/app/DashboardHandling.jsx",
    "frontend/workbench/app/DashboardWorkspace.jsx",
    "tests/workbench/dashboard_external_handling_widgets_support.py",
    "tests/workbench/dashboard_external_handling_widgets_probe.cjs",
    "tests/workbench/outsourcing_widgets_support.py",
    "tests/workbench/outsourcing_support.py",
    "tests/workbench/test_live_browser.py",
    "tests/workbench/live_environment.py",
    "scripts/workbench/compile.cjs",
    "static/workbench/asset-manifest.json",
    "frontend/workbench/prototype/ui_kits/workbench/assets/vendor/babel-7.29.0.min.js",
    "tests/workbench/fixtures/schema-v29.sql",
)
_SYSTEM_RESTORE_BROWSER_SCOPES = (
    "frontend/workbench/app/SystemRestoreStatus.js",
    "frontend/workbench/app/SystemMaintenanceAPI.js",
    "frontend/workbench/app/SystemMaintenanceControls.jsx",
    "frontend/workbench/app/SystemRestorePanel.jsx",
    "frontend/workbench/app/SystemMaintenanceRecords.jsx",
    "frontend/workbench/app/SystemMaintenanceConfig.jsx",
    "frontend/workbench/app/SystemMaintenanceWorkspace.jsx",
    "frontend/workbench/app/SystemLive.jsx",
    "frontend/workbench/app/ResourceControls.jsx",
    "web/bootstrap/workbench_system_restore_status.py",
    "web/bootstrap/workbench_system_restore_view.py",
    "templates/workbench/recovery.html",
    "tests/workbench/system_restore_entrypoint_support.py",
    "tests/workbench/system_restore_entrypoint_process_support.py",
    "tests/workbench/system_restore_host_support.py",
    "tests/workbench/du_system_restore_browser.cjs",
    "tests/workbench/system_maintenance_widgets_probe.cjs",
    "tests/workbench/system_config_saved_probe.cjs",
    "tests/workbench/test_live_browser.py",
    "tests/workbench/live_environment.py",
    "scripts/workbench/build-order.json",
    "scripts/workbench/compile.cjs",
    "static/workbench/asset-manifest.json",
    "frontend/workbench/prototype/ui_kits/workbench/assets/vendor/babel-7.29.0.min.js",
)
_DELIVERED_POINT_BROWSER_SCOPES = (
    "frontend/workbench/app/PointContract.js", "frontend/workbench/app/PointGanttModel.js",
    "frontend/workbench/app/PointGantt.jsx", "frontend/workbench/app/PlanGanttCanvas.jsx",
    "frontend/workbench/app/PlanGantt.jsx", "frontend/workbench/app/PlanContract.js",
    "tests/workbench/point_frontend_support.py", "tests/workbench/point_frontend_probe.cjs",
    "tests/workbench/point_browser_build.cjs", "tests/workbench/point_browser_host.jsx",
    "tests/workbench/point_browser_probe.cjs", "tests/workbench/point_dense_canvas_probe.cjs",
    "tests/workbench/point_downstream_support.py", "tests/workbench/point_downstream_browser.cjs",
    "tests/workbench/point_downstream_browser_build_support.cjs",
    "tests/workbench/el_material_contracts.cjs", "tests/workbench/el_material_paging.cjs",
    "frontend/workbench/app/resource-contract.js", "frontend/workbench/app/ResourceWorkspace.jsx",
)
_DELIVERED_MAIN_PAGE_SCOPES = (
    "tests/workbench/merged_cycle_ui_contract.cjs", "tests/workbench/merged_cycle_projection_support.py",
    "tests/workbench/merged_cycle_ui_runner.py", "tests/workbench/merged_cycle_ui_server.py",
    "tests/workbench/merged_cycle_ui_assets.py", "tests/workbench/merged_cycle_ui_seed.py",
    "tests/workbench/merged_cycle_ui_probe.cjs", "tests/workbench/merged_cycle_ui_steps.cjs",
    "tests/workbench/secondary_copy_assets.py", "tests/workbench/secondary_copy_server.py",
    "tests/workbench/secondary_copy_component_probe.cjs", "tests/workbench/secondary_copy_live_probe.cjs",
    "tests/workbench/secondary_copy_metrics.cjs", "tests/workbench/az_contrast_modal_harness.cjs",
    "tests/workbench/az_contrast_modal_fixture.jsx", "frontend/workbench/app/WorkbenchControlStyles.jsx",
    "tests/workbench/ed_material_process_server.py", "tests/workbench/ed_material_process_seed.py",
    "tests/workbench/ed_material_process_assets.py", "tests/workbench/ed_material_process_probe.cjs",
    "tests/workbench/ed_material_process_material.cjs", "tests/workbench/ed_material_process_filters.cjs",
    "tests/workbench/ed_material_process_stages.cjs", "tests/workbench/ed_material_process_states.cjs",
    "tests/workbench/ed_material_process_visual.cjs", "tests/workbench/migrated_process_batch_support.cjs",
    "tests/workbench/el_material_server.py", "tests/workbench/el_material_assets.py",
    "tests/workbench/el_material_probe.cjs", "tests/workbench/el_material_actions.cjs",
    "tests/workbench/reports_review_browser_server.py", "tests/workbench/reports_review_browser_seed.py",
    "tests/workbench/reports_review_browser_oracle.py", "tests/workbench/reports_review_browser_probe.cjs",
    "tests/workbench/reports_review_browser_actions.cjs", "tests/workbench/reports_review_browser_details.cjs",
    "tests/workbench/reports_review_browser_support.cjs",
    "tests/workbench/run_live_server.py", "tests/workbench/run_live_server_support.py",
    "tests/workbench/live_environment.py", "tests/workbench/test_live_browser.py",
    "frontend/workbench/app/ResourceForms.jsx", "frontend/workbench/app/ResourceWorkspace.jsx",
    "frontend/workbench/app/resource-contract.js", "frontend/workbench/app/ProcessDetail.jsx",
    "frontend/workbench/app/ProcessRouteEntry.jsx", "frontend/workbench/app/ProcessSourceEditor.jsx",
    "frontend/workbench/app/ProcessHoursEditor.jsx", "frontend/workbench/app/ProcessStageEditor.jsx",
    "frontend/workbench/app/Report*", "frontend/workbench/app/Review*",
    "scripts/workbench/build-order.json", "scripts/workbench/compile.cjs",
    "static/workbench/asset-manifest.json",
)
_DELIVERED_PIECE_BROWSER_SCOPES = (
    "tests/workbench/piece_downstream_contract.cjs", "tests/workbench/piece_downstream_browser.cjs",
    "tests/workbench/piece_downstream_browser_support.cjs", "tests/workbench/test_piece_main_browser.py",
    "frontend/workbench/app/FieldContract.js", "frontend/workbench/app/FieldTable.jsx",
    "frontend/workbench/app/FieldDetail.jsx", "frontend/workbench/app/ActualGanttContract.js",
    "frontend/workbench/app/ActualGanttModel.js", "frontend/workbench/app/ActualGanttRows.jsx",
    "core/services/workbench/field_workspace.py", "core/services/workbench/field_workspace_scope.py",
    "core/services/workbench/actual_gantt_scope.py", "core/services/workbench/actual_gantt_export.py",
    "tests/workbench/piece_main_server.py", "tests/workbench/piece_main_seed.py",
    "tests/workbench/piece_main_oracle.py", "tests/workbench/piece_main_build.cjs",
    "tests/workbench/piece_main_browser.cjs", "tests/workbench/piece_main_actions.cjs",
    "tests/workbench/piece_main_dependencies.cjs", "tests/workbench/piece_main_recovery.cjs",
    "tests/workbench/piece_main_visuals.cjs",
    "tests/workbench/piece_presentation_build.cjs", "tests/workbench/piece_presentation_host.jsx",
    "tests/workbench/piece_presentation_browser.cjs", "tests/workbench/piece_presentation_contract.cjs",
    "tests/workbench/test_piece_presentation.py", "tests/workbench/test_piece_chain_end_to_end.py",
    "tests/workbench/piece_chain_support.py", "tests/workbench/point_frontend_support.py",
    "tests/workbench/run_candidate_baseline_support.py", "tests/workbench/run_candidate_support.py",
    "tests/workbench/plan_catalog_support.py", "tests/workbench/trial_support.py",
    "tests/workbench/plan_ui_fixtures.cjs", "tests/workbench/live_environment.py",
    "tests/workbench/test_live_browser.py", "tests/workbench/run_live_server.py",
    "tests/workbench/run_live_server_support.py",
    "frontend/workbench/app/main.jsx", "frontend/workbench/app/resource-contract.js",
    "frontend/workbench/app/PointContract.js", "frontend/workbench/app/PlanContract.js",
    "frontend/workbench/app/PointGanttModel.js", "frontend/workbench/app/PlanGanttModel.js",
    "frontend/workbench/app/RunCandidateAPI.js", "frontend/workbench/app/RunCandidateModel.js",
    "frontend/workbench/app/RunBaselineAPI.js", "frontend/workbench/app/RunBaselineModel.js",
    "frontend/workbench/app/TrialDetails.jsx", "frontend/workbench/app/TrialGantt.jsx",
    "scripts/workbench/build-order.json", "scripts/workbench/compile.cjs",
    "static/workbench/asset-manifest.json",
    "frontend/workbench/prototype/ui_kits/workbench/assets/vendor/babel-7.29.0.min.js",
)
_DELIVERED_PLAN_BROWSER_SCOPES = (
    "tests/workbench/plan_scope_caption_probe.cjs",
    "tests/workbench/fg_plan_workspace_actions_probe.cjs",
    "tests/workbench/plan_adoption_baseline_support.py",
    "tests/workbench/plan_ui_browser_probe.cjs", "tests/workbench/plan_ui_browser_harness.cjs",
    "tests/workbench/point_downstream_browser_build_support.cjs",
    "tests/workbench/point_downstream_support.py", "tests/workbench/ea_zero_duration_support.py",
    "tests/workbench/run_candidate_support.py", "tests/workbench/trial_support.py",
    "web/routes/workbench/plan_reads.py", "core/services/workbench/plan_projection.py",
    "frontend/workbench/app/PlanWorkspace.jsx", "frontend/workbench/app/PlanLayout.jsx",
    "frontend/workbench/app/PlanContract.js", "frontend/workbench/app/PlanAPI.js",
    "frontend/workbench/app/PointContract.js", "frontend/workbench/app/main.jsx",
    "scripts/workbench/build-order.json", "scripts/workbench/compile.cjs",
    "static/workbench/asset-manifest.json",
    "frontend/workbench/prototype/ui_kits/workbench/assets/vendor/babel-7.29.0.min.js",
)

_FINAL_CAPACITY_INPUT_SCOPES = (
    # The managed source freeze reads every product input, not just scheduling code.
    "*.py", "core/**/*.py", "data/**/*.py", "web/**/*.py", "plugins/**/*.py",
    "frontend/workbench/**/*", "templates/workbench/**/*",
    "tests/workbench/final_capacity_assets.py",
    "tests/workbench/final_capacity_observation.py",
    "tests/workbench/final_capacity_probe.py",
    "tests/workbench/final_capacity_server.py",
    "tests/workbench/final_capacity_sources.py",
    "tests/workbench/final_capacity_support.py",
    "tests/workbench/final_capacity_binding.py",
    "tests/workbench/final_foundation_live_source_guard.py",
    ".codestable/roadmap/workbench-prototype-migration/legacy-retirement/factory-tests/source_guard.py",
    ".codestable/roadmap/workbench-prototype-migration/legacy-retirement/factory-tests/source_binding.py",
    ".codestable/roadmap/workbench-prototype-migration/legacy-retirement/factory-tests/source_inventory.py",
    "scripts/workbench/verify_final_capacity.py",
    "tests/workbench/live_environment.py",
    "tests/workbench/run_live_server.py",
    "tests/workbench/run_live_server_support.py",
)
_FINAL_CAPACITY_ENV_KEYS = (
    "FACTORY_SOURCE_MANIFEST", "WORKBENCH_CAPACITY_EXPECTED_SOURCE_ROOT",
    "WORKBENCH_CAPACITY_FORBIDDEN_ORIGIN", "WORKBENCH_CAPACITY_MANIFEST_SHA256",
)

WORKBENCH_SUPPLEMENTAL_REGRESSION_GROUPS = (
    _group("workbench_browser", "Heavy Chrome109 probes; installed runtime and current assets required", (
        "test_live_browser.py", "test_resource_live_browser.py",
        "test_resource_readiness.py", "test_resource_details_widgets.py",
        "test_resource_detail_layout.py", "test_resource_file_widgets.py",
        "test_resource_navigation_context.py", "test_resource_table_header_widgets.py",
        "test_process_live_browser.py", "test_process_widgets.py",
        "test_process_actions_widgets.py", "test_process_detail_files.py",
        "test_process_readiness_browser.py", "test_process_stage_widgets.py",
        "test_batch_transport.py", "test_batch_widgets.py", "test_plan_ui.py",
        "test_master_overview_browser.py", "test_preflight_browser.py",
        "test_actual_gantt_ui.py", "test_be_preflight_actual_surfaces.py",
        "test_report_ledger_widgets.py", "test_report_widgets.py", "test_system_config_saved.py",
        "test_system_maintenance_widgets.py", "test_workbench_plain_language.py",
        "test_workspace_primitive_styles.py",
        "test_run_job_widgets.py", "test_run_candidate_widgets.py", "test_run_history_widgets.py",
        "test_run_live_server.py",
        "test_run_presentation.py", "test_run_baseline_widgets.py",
        "test_calibration_widgets.py",
        "test_run_adoption_widgets.py", "test_calibration_lineage_ui.py",
        "test_trial_widgets.py", "test_calibration_adoption_widgets.py",
        "test_trial_adoption_widgets.py", "test_trial_export_widgets.py",
        "test_dashboard_widgets.py", "test_plan_adoption_baseline_browser.py",
        "test_trial_adoption_history_widgets.py",
        "test_process_quota_widgets.py",
        "test_outsourcing_widgets.py",
        "test_dashboard_external_handling_widgets.py",
        "test_du_system_restore_browser.py",
        # Node-only execution still requires runtime_tools' installed browser path.
        "test_du_system_restore_contract.py",
        "test_point_frontend.py", "test_point_downstream_browser.py",
        # EL's Node probes also call runtime_tools before launching Node.
        "test_el_material_contracts.py", "test_point_dense_canvas.py",
        "test_piece_main_browser.py", "test_piece_presentation_browser.py",
        # EV executes Node only, but runtime_tools still requires installed Chrome.
        "test_ev_piece_fixture_contracts.py",
        # FA has no skip marker, but builds a private UI and launches real Chrome109.
        "test_plan_scope_caption.py",
        "test_fg_plan_workspace_actions.py",
        # The API file also invokes runtime_tools for its Node model contract.
        "test_piece_downstream_api.py", "test_piece_downstream_browser.py",
        "test_round1_field_piece_files_browser.py",
        # Final shell companions share the browser owner; registration is not execution.
        "test_final_foundation_navigation.py", "test_final_foundation_live.py",
        "test_final_navigation_host.py", "test_final_navigation_boot.py",
        "test_final_legacy_navigation.py",
        "test_final_execution_analytics.py",
        "test_final_execution_backend.py",
        "test_final_execution_browser.py",
        "test_final_execution_calibration.py",
        "test_final_execution_chain.py",
        "test_final_execution_controls.py",
        "test_final_execution_history.py",
        "test_final_execution_reports.py",
        "test_final_execution_search.py",
        "test_final_master_config_trace.py",
        "test_final_master_context.py",
        "test_final_master_guards.py",
        "test_final_master_manifest.py",
        "test_final_master_metadata_guard.py",
        "test_final_operations_analysis.py",
        "test_final_operations_browser.py",
        "test_final_operations_candidates.py",
        "test_final_operations_download.py",
        "test_final_operations_download_contract.py",
        "test_final_operations_host.py",
        "test_final_operations_pressure.py",
        "test_final_operations_projection_api.py",
        "test_final_operations_records.py",
        "test_final_operations_restore.py",
        "test_final_planning_browser.py",
        "test_final_planning_contracts.py",
        "test_final_planning_delivery.py",
        "test_final_planning_preflight_return.py",
        "test_final_planning_readonly.py",
        "test_final_legacy_navigation_layering.py", "test_final_planning_gantt.py",
        "test_final_operations_read_controls.py",
        "test_final_execution_calibration_table.py", "test_final_execution_resources.py",
        "test_final_legacy_report_dates.py",
        "test_final_operations_edges.py", "test_final_operations_inflight.py",
        "test_final_master_action_ledger.py", "test_final_master_config_preservation.py",
        "test_final_master_resource_revisions.py",
        "test_final_operations_navigation.py",
        "test_final_operations_system_recovery.py",
        "test_final_operations_system_restart.py",
        "test_final_planning_process_order.py",
        "test_final_planning_task_origin.py",
        "test_final_planning_required.py",
        "test_batch_dashboard_return_context.py",
        "test_final_planning_l5_contract.py",
        "test_final_execution_read_contract.py",
        "test_final_execution_read_reentry.py",
        "test_final_execution_rejections.py",
        "test_final_execution_report_contract.py",
        "test_final_execution_report_reentry.py",
        "test_final_master_typed_lineage.py",
        "test_final_operations_context_contract.py",
        "test_final_planning_candidate_source.py",
        "test_final_master_domain_ledger.py",
    ), (*_BROWSER_SCOPES, *_DASHBOARD_EXTERNAL_BROWSER_SCOPES, *_SYSTEM_RESTORE_BROWSER_SCOPES,
        *_DELIVERED_POINT_BROWSER_SCOPES, *_DELIVERED_PIECE_BROWSER_SCOPES,
        *_DELIVERED_PLAN_BROWSER_SCOPES,
        "tests/workbench/test_round1_field_piece_files_browser.cjs",
        "tests/workbench/round1_field_piece_files_probe.py",
        "tests/workbench/round1_field_piece_files_support.py",
        "tests/workbench/field_workspace_probe_harness.cjs",
        ".codestable/roadmap/workbench-prototype-migration/workbench-capabilities.json",
        ".codestable/roadmap/workbench-prototype-migration/acceptance-master/actions.json",
        ".codestable/roadmap/workbench-prototype-migration/acceptance-planning/action-inventory.json",
    ), (
        *_BROWSER_ENV_KEYS, "PIECE_MAIN_ALL_THEMES", "PIECE_MAIN_LONG_IDS", "WORKBENCH_EV_SOURCE_ROOT",
        "WORKBENCH_EXPECT_BUILD", "SYSTEM_CONFIG_SAVED_REPLAY_OLD_EFFECT",
        "TRIAL_WIDGET_TARGET_ONLY", "OUTSOURCING_UI_SCHEMA",
        "FINAL_E_PARENT",
        "FINAL_E_SHARED_BUILD",
        "FINAL_E_SHARED_BUILD_ID",
        "FINAL_OPERATIONS_BUILD",
        "FINAL_PLANNING_BUILD",
        "FINAL_PLANNING_TEMP_PARENT",
    )),
    _group("workbench_browser_opt_in", "Opt-in browser probes; skipped collection is not execution", (
        "test_migrated_process_batch_browser.py", "test_process_stage_live_browser.py",
        "test_modal_focus_browser.py", "test_az_contrast_modal_scroll.py",
        "test_asset_browser_globals.py",
        "test_ed_material_process_browser.py", "test_el_material_browser.py",
        "test_reports_review_browser.py",
        "test_merged_cycle_ui.py", "test_secondary_copy_contrast.py",
    ), (*_BROWSER_SCOPES, *_DELIVERED_MAIN_PAGE_SCOPES), (
        *_BROWSER_ENV_KEYS, "AN_RUN_BROWSER", "AN_STATES", "AN_SCOPE", "AZ_RUN_BROWSER",
        # The pytest entry strips AY_SMOKE, AY_BASELINE and AY_UNSUSPENDED before launch.
        "AY_RUN_MODAL_FOCUS", "AY_REACT_DEV", "WORKBENCH_PROCESS_STAGE_BUILD_READY",
        "WORKBENCH_PROCESS_STAGE_SCOPE",
        "ED_RUN_BROWSER", "ED_CANDIDATE", "ED_STATES", "ED_SCOPE",
        "EL_RUN_BROWSER", "EL_CANDIDATE", "EL_STATES", "EI_RUN_BROWSER", "AN_PYTHON",
        "ER_RUN_BROWSER", "SECONDARY_COPY_RUN_BROWSER", "SECONDARY_COPY_BASELINE",
    )),
    _group("workbench_run_compute_capacity", "Heavy 5000-operation compute; explicit run, not a quick check", (
        "test_run_compute_capacity.py",
        "test_final_capacity_cli_loading.py",
        "test_final_capacity_contract.py", "test_final_capacity_inputs.py",
        "test_final_capacity_source_binding.py",
    ), (
        *_PLAN_READ_SCOPES,
        *_FINAL_CAPACITY_INPUT_SCOPES,
        "core/models/workbench_run_compute.py", "core/services/workbench/run_compute*.py",
        "core/services/workbench/run_input*.py", "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/algorithm*/**/*.py", "core/services/scheduler/**/*.py", "data/repositories/*.py",
    ), _FINAL_CAPACITY_ENV_KEYS),
    _group("workbench_run_jobs_capacity", "Heavy 5000-task durable candidates; explicit capacity run", (
        "test_run_jobs_capacity.py",
        "test_final_capacity_managed.py",
    ), (
        *_PLAN_READ_SCOPES,
        *_FINAL_CAPACITY_INPUT_SCOPES,
        "core/models/workbench_run*.py", "core/services/workbench/run_*.py",
        "core/services/workbench/preflight*.py", "core/services/workbench/execution_ledger*.py",
        "core/services/execution/**/*.py",
        "core/algorithm*/**/*.py", "core/services/scheduler/**/*.py", "data/repositories/*.py",
        "web/routes/workbench/scheduling_jobs.py",
    ), _FINAL_CAPACITY_ENV_KEYS),
    _group("workbench_system_platform", "System reads include host-dependent symlink skips", (
        "test_system_reads.py",
    ), (
        "core/services/system/**/*.py", "core/services/workbench/system*.py",
        "web/routes/workbench/system*.py", "tests/workbench/system_contract_probe.cjs",
        "frontend/workbench/app/System*",
    )),
    _group("workbench_asset_build", "Build-host asset tests; explicit build/browser validation only", (
        "test_assets_build.py", "test_asset_script_scopes.py", "test_pending_build_sources.py",
    ), _BROWSER_SCOPES, _BROWSER_ENV_KEYS),
    _group("workbench_run_history_capacity", "Heavy 350-run directory and 5000-candidate read contracts", (
        "test_run_history_capacity.py",
    ), _RUN_SCOPES),
    _group("workbench_run_candidate_capacity", "Heavy 5000-task candidate reads and complete exports", (
        "test_run_candidate_capacity.py",
    ), _RUN_SCOPES),
    _group("workbench_run_baseline_capacity", "Complete admission baseline with 5000 candidate tasks", (
        "test_run_candidate_baseline_capacity.py",
    ), _RUN_SCOPES),
    _group("workbench_run_adoption_capacity", "Candidate adoption scale and historical data preservation", (
        "test_run_candidate_adoption_capacity.py",
    ), _RUN_SCOPES),
    _group("workbench_calibration_capacity", "Calibration instance and complete export limits", (
        "test_calibration_scale.py",
    ), _BROWSER_SCOPES),
    _group("workbench_identity_diagnostics", "Frozen v29 collision baseline and additive guards; historical cause unresolved", (
        "test_plan_identity_insert_collision.py",
    ), _RUN_SCOPES),
    _group("workbench_trial_capacity", "Trial preservation with 1000 and 10000 original tasks", (
        "test_trial_scale.py",
    ), _TRIAL_SCOPES),
    _group("workbench_lineage_lookup_capacity", "Lineage lookup VM budgets and 5000 to 10000 row preservation", (
        "test_lineage_lookup_budget.py",
    ), (
        *_LINEAGE_SCOPES,
        "tests/workbench/plan_identity_support.py",
        "tests/workbench/test_plan_persistent_identity.py",
    )),
    _group("workbench_dashboard_capacity", "Heavy dashboard reads and complete-source admission limits", (
        "test_dashboard_capacity.py",
    ), _DASHBOARD_SCOPES),
)
