from __future__ import annotations

import os

from tools.test_registry_algorithm_efficiency import ALGORITHM_EFFICIENCY_REQUIRED_TESTS
from tools.test_registry_groups_workbench import WORKBENCH_REQUIRED_TESTS
from tools.test_registry_workbench_ui import WORKBENCH_UI_REQUIRED_TESTS

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

QUALITY_GATE_SELFTEST_PATH = "tests/gate_meta/test_run_quality_gate.py"

QUALITY_GATE_STARTUP_REGRESSION_ARGS = (
    "tests/app_runtime/test_runtime_probe_resolution.py",
    "tests/app_runtime/test_win7_launcher_runtime_paths.py",
    "tests/app_runtime/test_runtime_contract_launcher.py",
    "tests/app_runtime/test_entrypoint_meta_failure_visible.py",
    "tests/app_runtime/test_launcher_observability.py",
    "tests/app_runtime/test_runtime_lock_reloader_parent_skip.py",
    "tests/app_runtime/test_startup_host_portfile.py",
    "tests/app_runtime/test_startup_host_portfile_new_ui.py",
    "tests/config/test_plugin_bootstrap_config_failure_visible.py",
    "tests/config/test_plugin_bootstrap_injects_config_reader.py",
    "tests/app_runtime/test_plugin_bootstrap_telemetry_failure_visible.py",
    "tests/app_runtime/test_app_new_ui_secret_key_runtime_ensure.py",
    "tests/app_runtime/test_app_new_ui_session_contract.py",
    "tests/app_runtime/test_app_new_ui_security_hardening_enabled.py",
    "tests/app_runtime/test_app_factory_runtime_env_refresh.py",
    "tests/app_runtime/test_runtime_stop_cli.py",
    "tests/app_runtime/test_runtime_stop_draining.py",
)

QUALITY_GATE_GUARD_TESTS = (
    *ALGORITHM_EFFICIENCY_REQUIRED_TESTS,
    "tests/gate_meta/test_no_residual_main_style_regression.py",
    "tests/gate_meta/test_sp05_path_topology_contract.py",
    "tests/gate_meta/test_win7_networkx_package_contract.py",
    "tests/gate_meta/test_frozen_bundle_contract.py",
    "tests/schedule/service/test_schedule_input_builder_strict_hours_and_ext_days.py",
    "tests/algorithm/test_due_exclusive_consistency.py",
    "tests/calendar_maintenance/test_freeze_window_bounds.py",
    "tests/schedule/service/test_schedule_orchestrator_contract.py",
    "tests/schedule/service/test_schedule_params_direct_call_contract.py",
    "tests/config/test_config_field_spec_contract.py",
    "tests/config/test_scheduler_config_manual_url_normalization.py",
    "tests/config/test_config_service_active_preset_custom_sync.py",
    "tests/config/test_config_snapshot_strict_numeric.py",
    "tests/config/test_config_snapshot_projection_sync.py",
    "tests/config/test_scheduler_config_spec_sync_contract.py",
    "tests/config/test_config_service_component_contract.py",
    "tests/config/test_config_service_relaxed_missing_visible.py",
    "tests/config/test_apply_preset_adjusted_marks_custom.py",
    "tests/algorithm/test_schedule_summary_contract.py",
    "tests/schedule/route_view/test_scheduler_missing_resource_message.py",
    "tests/models_domain/test_strict_parse_blank_required.py",
    "tests/models_domain/test_schedule_resource_filter.py",
    "tests/gantt/test_gantt_adapter_contract.py",
    "tests/gantt/test_gantt_adjustment_draft_model.py",
    "tests/gantt/test_gantt_draft_save_and_preview.py",
    "tests/gantt/test_gantt_scenario_publish.py",
    "tests/gantt/test_frappe_gantt_short_task_contract.py",
    "tests/gantt/test_gantt_readonly_mode_contract.py",
    "tests/gantt/test_gantt_zoom_contract.py",
    "tests/gantt/test_gantt_zoom_decoration_sync.py",
    "tests/gantt/test_gantt_zoom_range_guard.py",
    "tests/gantt/test_gantt_task_labels_contract.py",
    "tests/gantt/test_gantt_url_persistence.py",
    "tests/gantt/test_gantt_frontend_error_boundary.py",
    "tests/scheduler_analysis/test_report_context_filters_contract.py",
    "tests/web_pages/test_report_plan_filter_js_contract.py",
    "tests/scheduler_analysis/test_report_delay_diagnosis_plain_language.py",
    "tests/operation_execution/test_execution_review_identity_guard.py",
    "tests/web_pages/test_web_silent_fallback_contract.py",
    "tests/scheduler_analysis/test_plan_vs_actual_review.py",
    "tests/schedule/route_view/test_scheduler_plan_identity_evidence_contract.py",
    "tests/schedule/route_view/test_scheduler_plan_identity_evidence_link_contract.py",
    "tests/schedule/route_view/test_scheduler_plan_identity_summary_guard.py",
    "tests/web_pages/test_workbench_nav_entry_contract.py",
    "tests/gate_meta/test_quality_gate_output_normalization.py",
    "tests/gantt/test_gantt_critical_chain_unavailable.py",
    "tests/gantt/test_gantt_critical_chain_provider.py",
    "tests/gantt/test_scheduler_candidate_gantt_plan_role_contract.py",
    "tests/candidate/test_scheduler_candidate_plan_query_contract.py",
    "tests/candidate/test_scheduler_candidate_summary_contract.py",
    "tests/scheduler_graph/test_scheduler_graph_on_mode_contract.py",
    "tests/algorithm/test_sgs_scoring_fallback_unscorable.py",
    "tests/candidate/test_scheduler_candidate_runner_contract.py",
    "tests/candidate/test_scheduler_candidate_persistence_contract.py",
    "tests/candidate/test_scheduler_candidate_corrections_contract.py",
    "tests/gate_meta/test_quality_gate_scan_contract.py",
    "tests/gate_meta/test_aps_three_gap_docs_quality_gate.py",
    "tests/gate_meta/test_codestable_architecture_contract.py",
    "tests/gate_meta/test_codestable_tools_contract.py",
    "tests/gate_meta/test_symbol_locator_contract.py",
    "tests/web_pages/test_factory_request_lifecycle_observability.py",
    "tests/calendar_maintenance/test_maintenance_window_mutex.py",
    "tests/migration_db/test_database_high_version_failfast.py",
    "tests/algorithm/test_optimizer_seed_results_contract.py",
    "tests/algorithm/test_optimizer_seed_boundary_contract.py",
    "tests/algorithm/test_optimizer_runtime_seam_contract.py",
    "tests/algorithm/test_optimizer_outcome_type_contract.py",
    "tests/algorithm/test_optimizer_search_report_contract.py",
    "tests/algorithm/test_optimizer_public_summary_projection_contract.py",
    "tests/algorithm/test_optimizer_proof_harness_contract.py",
    "tests/algorithm/test_optimizer_candidate_profile_contract.py",
    "tests/algorithm/test_optimizer_candidate_fingerprint_contract.py",
    "tests/algorithm/test_optimizer_grasp_ig_candidate_construction_contract.py",
    "tests/algorithm/test_optimizer_business_neighborhood_registry_contract.py",
    "tests/algorithm/test_optimizer_vns_sa_local_search_contract.py",
    "tests/algorithm/test_optimizer_graph_ready_candidate_contract.py",
    "tests/algorithm/test_optimizer_benchmark_ratchet_gate.py",
    "tests/algorithm/test_optimizer_ratchet_baseline_lifecycle.py",
    "tests/algorithm/test_optimizer_quality_matrix_contract.py",
    "tests/algorithm/test_optimizer_profile_predecode_dedup.py",
    "tests/algorithm/test_optimizer_profile_budget.py",
    "tests/algorithm/test_incomplete_batch_metrics_contract.py",
    "tests/algorithm/test_incomplete_batch_optimizer_contract.py",
    "tests/algorithm/test_incomplete_metrics_public_projection.py",
    "tests/algorithm/test_incomplete_batch_objective_completed_subset_contract.py",
    "tests/algorithm/test_sgs_working_hour_slack_dispatch.py",
    "tests/resource_dispatch/test_dispatch_rules_working_hour_priority_contract.py",
    "tests/calendar_maintenance/test_calendar_working_hours_between.py",
    "tests/algorithm/test_ready_date_resource_calendar_lower_bound.py",
    "tests/algorithm/test_sgs_slot_reuse_contract.py",
    "tests/algorithm/test_sgs_slot_reuse_equivalence.py",
    "tests/algorithm/test_busy_block_native_equivalence.py",
    "tests/algorithm/test_busy_block_boundaries.py",
    "tests/algorithm/test_sgs_explicit_piece_scope.py",
    "tests/schedule/service/test_unselected_execution_resource_guardrails.py",
    "tests/schedule/service/test_unselected_execution_resource_fail_closed.py",
    "tests/schedule/service/test_unselected_execution_resource_snapshot.py",
    "tests/schedule/service/test_unselected_execution_feedback_continuity.py",
    "tests/schedule/service/test_schedule_seed_metadata_helper_contract.py",
    "tests/gantt/test_gantt_critical_chain_cache_snapshot.py",
    "tests/gantt/test_gantt_critical_chain_cache_transactions.py",
    "tests/scheduler_analysis/test_report_calendar_capacity_intersections.py",
    "tests/material/test_material_finite_quantity_contract.py",
    "tests/algorithm/test_localsearch_batch_order_actuator.py",
    "tests/schedule/service/test_schedule_input_collector_contract.py",
    "tests/schedule/service/test_schedule_input_collector_legacy_compat.py",
    "tests/schedule/service/test_schedule_service_missing_resource_source_case_insensitive.py",
    "tests/schedule/service/test_schedule_service_reschedulable_contract.py",
    "tests/schedule/service/test_schedule_params_read_failure_visible.py",
    "tests/schedule/service/test_schedule_service_strict_snapshot_guard.py",
    "tests/config/test_schedule_config_snapshot_optional_guard.py",
    "tests/schedule/service/test_schedule_service_facade_delegation.py",
    "tests/schedule/service/test_schedule_persistence_reject_empty_actionable_schedule.py",
    "tests/schedule/service/test_schedule_persistence_reschedulable_contract.py",
    "tests/algorithm/test_schedule_optimizer_cfg_snapshot_contract.py",
    "tests/schedule/summary/test_schedule_summary_cfg_snapshot_contract.py",
    "tests/schedule/summary/test_schedule_summary_algo_warnings_union.py",
    "tests/schedule/summary/test_schedule_summary_invalid_due_and_unscheduled_counts.py",
    "tests/schedule/summary/test_schedule_summary_freeze_state_contract.py",
    "tests/schedule/summary/test_schedule_summary_overdue_warning_append_fallback.py",
    "tests/schedule/summary/test_schedule_summary_v11_contract.py",
    "tests/schedule/summary/test_schedule_summary_merge_context_degraded_code.py",
    "tests/schedule/summary/test_schedule_summary_input_fallback_contract.py",
    "tests/scheduler_analysis/test_scheduler_delay_diagnosis_contract.py",
    "tests/schedule/service/test_scheduler_exception_blocks_auto_reschedule.py",
    "tests/scheduler_graph/test_scheduler_graph_auto_selection_contract.py",
    "tests/scheduler_graph/test_scheduler_graph_report_mode_service_contract.py",
    "tests/schedule/service/test_schedule_template_lookup_contract.py",
    "tests/resource_dispatch/test_resource_dispatch_bad_time_rows_surface_degraded.py",
    "tests/resource_dispatch/test_resource_dispatch_task_id_encoding.py",
    "tests/migration_db/test_migration_schema_contract.py",
    "tests/migration_db/test_migrations.py",
    "tests/operation_execution/test_operation_execution_event_foundation.py",
    "tests/operation_execution/test_operation_execution_event_sequence_contract.py",
    "tests/operation_execution/test_operation_execution_event_time_contract.py",
    "tests/operation_execution/test_operation_execution_state_revision.py",
    "tests/operation_execution/test_operation_execution_state_flow.py",
    "tests/operation_execution/test_operation_execution_scope_read_contract.py",
    "tests/operation_execution/test_operation_execution_migration_v16_contract.py",
    "tests/operation_execution/test_operation_execution_migration_v18_contract.py",
    "tests/operation_execution/test_operation_execution_migration_v19_contract.py",
    "tests/operation_execution/test_scheduler_reschedule_execution_facts.py",
    "tests/schedule/service/test_scheduler_reschedule_execution_minimum_guard.py",
    "tests/gantt/test_gantt_adjustment_publish_execution_revision.py",
    "tests/excel_data_io/test_import_execution_stats_source_row_num.py",
    "tests/resource_dispatch/test_resource_dispatch_overdue_summary_formats.py",
    "tests/resource_dispatch/test_resource_dispatch_workbench_lane_contract.py",
    "tests/web_pages/test_error_field_label_source.py",
    "tests/gate_meta/test_run_full_selftest_report_metadata.py",
    "tests/gate_meta/test_callgraph_receiver_resolution.py",
    "tests/gate_meta/test_import_cycle_scanner.py",
    "tests/gate_meta/test_import_cycle_baseline.py",
    "tests/gate_meta/test_round1_import_resolver.py",
    "tests/gate_meta/test_check_full_test_debt.py",
    "tests/app_runtime/test_fast_static_precheck.py",
    "tests/gate_meta/test_git_hook_checks.py",
    "tests/gate_meta/test_benchmark_full_test_debt_shards.py",
    "tests/gate_meta/test_long_gate_cli_controls.py",
    "tests/gate_meta/test_long_gate_quickref_cache.py",
    "tests/app_runtime/test_safe_next_url_hardening.py",
    "tests/app_runtime/test_fixed_file_security.py",
    "tests/app_runtime/test_validate_dist_runtime_identity.py",
    "tests/web_pages/test_system_runtime_log_reader.py",
    "tests/excel_data_io/test_excel_import_hardening.py",
    "tests/app_runtime/test_frontend_offline_static_assets.py",
    "tests/web_pages/test_error_boundary_contract.py",
    # 诊断包安全红线：zip 名单永不含 aps_secret_key.txt（fusion-runtime-log-viewer）
    # 打印介质契约：.sidebar 必须在 print 隐藏名单（fusion-anchor-baseline-prep）
    # 设计令牌真相源：定版色/暗色红线/裸 hex 冻结白名单/阈值单点（fusion-tokens-single-source）
    "tests/web_pages/test_css_token_source_contract.py",
    # 排产词表唯一字源：模板禁回潮内联字典/ok2 死键零现身（fusion-label-single-source）
    "tests/app_runtime/test_ui_browser_geometry_env.py",
    "tests/app_runtime/test_ui_geometry_html_contract.py",
    "tests/gate_meta/test_scan_py38plus_syntax.py",
    "tests/gate_meta/test_dead_code_usage_graph_contract.py",
    "tests/gate_meta/test_dead_code_usage_graph_scope_contract.py",
    "tests/gate_meta/test_anti_regression_gate.py",
    "tests/gate_meta/test_architecture_fitness.py",
    "tests/algorithm/test_skill_rank_mapping.py",
    "tests/schedule/service/test_schedule_service_input_merge_context_contract.py",
    # F6（2026-06-10）：loud/契约旁证补登增量门禁——坏数据不静默是灵魂线，这些断言必须随相关源改动被强制选中。
    # 备份/恢复/物料 4 个走 misc 组 request_services_runtime_error_boundary（scope 覆盖 core/infrastructure、web/routes/system_backup.py、data/**）。
    "tests/migration_db/test_backup_integrity_check_contract.py",
    "tests/migration_db/test_restore_pre_snapshot_failure_contract.py",
    "tests/material/test_material_repo_stock_qty_loud_contract.py",
    # 工序 seq / summary 元状态 / 候选基线四态 3 个走 scheduler 组（scope core/services/scheduler/**）。
    "tests/schedule/service/test_op_seq_loud_contract.py",
    "tests/schedule/summary/test_meta_bool_state_parity_contract.py",
    "tests/candidate/test_baseline_missing_or_failed_four_state_parity.py",
    # N4（2026-06-10）：R07 排程行缺失 NOT_FOUND 错误契约旁证（归 scheduler_run_core 组，
    # scope core/services/scheduler/** 覆盖 resource_dispatch_execution_service.py）。
    "tests/resource_dispatch/test_resource_dispatch_task_card_schedule_missing_contract.py",
    # R55（2026-06-10）：关键链 scope 标记契约（归 scheduler_analysis_gantt_reports_week_plan 组，
    # scope 覆盖 gantt_service_support.py / gantt_contract.py）。
    "tests/gantt/test_gantt_critical_chain_scope_contract.py",
    "tests/candidate/test_scheduler_candidate_schema_contract.py",
    "tests/gate_meta/test_scheduler_lazy_exports_final.py",
)

QUALITY_GATE_GUARD_TESTS = (*QUALITY_GATE_GUARD_TESTS, *WORKBENCH_REQUIRED_TESTS, *WORKBENCH_UI_REQUIRED_TESTS)
QUALITY_GATE_REQUIRED_TESTS = (QUALITY_GATE_SELFTEST_PATH, *QUALITY_GATE_GUARD_TESTS)

TEST_ONLY_HELPER_IMPACT = {
    "tests/_support/migration_schema_helpers.py": (
        "tests/algorithm/test_schedule_persistence_auto_assign_contract.py",
        "tests/calendar_maintenance/test_migrate_v2_unify_workcalendar_day_type.py",
        "tests/excel_data_io/test_sanitize_batch_dates_single_digit.py",
    ),
    "tests/gate_meta/long_gate_cache_helpers.py": (
        "tests/gate_meta/test_long_gate_debt_ledger_cache.py",
        "tests/gate_meta/test_long_gate_required_regression_cache.py",
        "tests/gate_meta/test_long_gate_startup_regression_cache.py",
    ),
    "tests/web_pages/reports_workbench_backlink_helpers.py": (
        "tests/scheduler_analysis/test_report_context_filters_contract.py",
    ),
}

REQUIRED_REGRESSION_COMMON_SCOPES = {
    "input_file_scopes": (
        "tests/conftest.py",
        "conftest.py",
        "tests/app_runtime/runtime_cleanup_helper.py",
    ),
    "config_file_scopes": (
        "pytest.ini",
        "pyproject.toml",
        "setup.cfg",
        "tox.ini",
        ".gitignore",
        "tools/test_registry.py",
        "tools/test_registry_data.py",
        "tools/test_registry_groups_misc.py",
        "tools/test_registry_groups_scheduler.py",
        "tools/test_registry_algorithm_efficiency.py",
        "tools/test_registry_groups_workbench.py",
        "tools/test_registry_workbench_ui.py",
        "tools/quality_gate_shared.py",
        "tools/quality_gate_support.py",
        "scripts/run_quality_gate.py",
        ".codestable/checkup/import_cycles_production_baseline.json",
        ".codestable/checkup/import_cycles_with_tests_baseline.json",
    ),
    "tool_file_scopes": (
        "scripts/run_quality_gate.py",
        "tools/fast_static_precheck.py",
        "tools/long_gate_cache.py",
        "tools/long_gate_collect.py",
        "tools/long_gate_fingerprint.py",
        "tools/long_gate_full_test_debt.py",
        "tools/long_gate_manifest.py",
        "tools/long_gate_paths.py",
        "tools/long_gate_schema.py",
        "tools/long_gate_summary.py",
        "tools/verify_required_regressions_from_full_test_debt.py",
        "tools/test_registry.py",
        "tools/test_registry_data.py",
        "tools/test_registry_groups_misc.py",
        "tools/test_registry_groups_scheduler.py",
        "tools/test_registry_algorithm_efficiency.py",
        "tools/test_registry_groups_workbench.py",
        "tools/test_registry_workbench_ui.py",
        "tools/quality_gate_shared.py",
        "tools/quality_gate_support.py",
        # scope 空洞审计(2026-06-23)补登：tools/scripts 下服务门禁运行/测试地基的工具脚本——
        # 改它们影响全套测试打标(full_test_debt_shards)、门禁扫描步骤(scan_*)、git hook 拦截
        # (git_hook_*)或门禁测量(benchmark/report/capture/build_test_inventory)，故纳入 common
        # 走全量，语义明确，取代原先"不命中任何 group → 漏网 fallback 全量"。desktop PyQt POC、
        # 业务转换脚本、空 __init__ 不在此列(非门禁工具，归 common 是错误语义)。
        "tools/architecture_scan_cache.py",
        "tools/benchmark_full_test_debt_shards.py",
        "tools/capture_networkx_phase0_baseline.py",
        "tools/full_test_debt_shards.py",
        "tools/git_hook_blocked_paths.py",
        "tools/git_hook_cache.py",
        "tools/report_full_test_debt_durations.py",
        "tools/scan_aps_three_gap_py38_scope.py",
        "tools/scan_dead_code_islands.py",
        "tools/import_cycle_*.py",
        "tools/scan_import_cycles.py",
        ".codestable/checkup/scripts/callgraph_*.py",
        "tools/dead_code_usage/**/*.py",
        "tools/scan_py38plus_syntax.py",
        "scripts/build_test_inventory.py",
    ),
    "dependency_file_scopes": (
        "requirements*.txt",
        "requirements-dev*.txt",
        "poetry.lock",
        "uv.lock",
        "Pipfile.lock",
    ),
    "env_keys": (
        "python_executable_realpath",
        "python_version",
        "pytest_version",
        "pytest_plugin_distribution_versions",
        "platform",
        "git_executable_realpath",
        "git_version",
        "PYTHONPATH",
        "PYTHONUTF8",
        "PYTHONIOENCODING",
        "PYTEST_ADDOPTS",
        "PYTEST_DISABLE_PLUGIN_AUTOLOAD",
        "PYTEST_PLUGINS",
    ),
}
