from __future__ import annotations

MISC_REQUIRED_REGRESSION_GROUPS = (
    {
        "group_id": "scheduler_batches_material_resource",
        "label": "Scheduler batches, material, and resource contracts",
        "target_paths": (
            "tests/regression_scheduler_batches_degraded_visibility.py",
            "tests/regression_scheduler_batch_template_warning_surface.py",
            "tests/regression_scheduler_resource_dispatch_invalid_query_cleanup.py",
            "tests/regression_resource_dispatch_bad_time_rows_surface_degraded.py",
            "tests/regression_resource_dispatch_export_surfaces_degraded.py",
            "tests/regression_resource_dispatch_public_output_contract.py",
            "tests/regression_resource_dispatch_viewmodel_public_output_contract.py",
            "tests/regression_resource_dispatch_task_id_encoding.py",
            "tests/regression_resource_dispatch_overdue_summary_formats.py",
            "tests/regression_resource_dispatch_invalid_summary_surfaces_overdue_degraded.py",
            "tests/regression_scheduler_excel_batches_preview_baseline_precision.py",
        ),
        "input_file_scopes": (
            "web/routes/domains/scheduler/scheduler_batches.py",
            "web/routes/domains/scheduler/scheduler_batch_detail.py",
            "web/routes/domains/scheduler/scheduler_excel_batches*.py",
            "web/routes/domains/scheduler/scheduler_resource_dispatch.py",
            "web/routes/domains/scheduler/scheduler_resource_dispatch_query.py",
            "web/routes/material.py",
            "web/routes/scheduler_batches.py",
            "web/routes/scheduler_batch_detail.py",
            "web/routes/scheduler_excel_batches.py",
            "web/routes/scheduler.py",
            "core/services/scheduler/**/*.py",
            # P0.3 收窄：data/templates_excel 由 owner 组（run_core / excel）覆盖故移除；
            # templates/static 收窄到 batches/material/resource 前端域。
            "templates/scheduler/batch*.html",
            "templates/scheduler/resource_dispatch.html",
            "templates/material/**/*.html",
            "templates/equipment/**/*.html",
            "static/js/batch_detail_linkage.js",
            "static/js/downtime_batch.js",
            "static/js/resource_dispatch*.js",
            "static/js/resource_execution*.js",
            "static/css/resource_dispatch.css",
            "app.py",
            "app_new_ui.py",
            "config.py",
            "schema.sql",
        ),
        "env_keys": (
            "APS_ENV",
            "APS_DB_PATH",
            "APS_EXCEL_TEMPLATE_DIR",
            "SECRET_KEY",
        ),
    },
    {
        "group_id": "request_services_runtime_error_boundary",
        "label": "Request services, runtime, and error boundary contracts",
        "target_paths": (
            "tests/regression_request_services_contract.py",
            "tests/regression_factory_request_lifecycle_observability.py",
            "tests/regression_system_request_services_contract.py",
            "tests/calendar_maintenance/test_maintenance_window_mutex.py",
            "tests/migration_db/test_database_high_version_failfast.py",
            "tests/migration_db/test_migration_schema_contract.py",
            "tests/migration_db/test_migrations.py",
            "tests/regression_operation_execution_migration_v16_contract.py",
            "tests/regression_operation_execution_migration_v18_contract.py",
            "tests/regression_operation_execution_migration_v19_contract.py",
            "tests/regression_error_field_label_source.py",
            "tests/regression_scheduler_data_route_error_contract.py",
            "tests/test_ui_mode.py",
            "tests/regression_safe_next_url_hardening.py",
            "tests/regression_safe_next_url_observability.py",
            "tests/regression_error_boundary_contract.py",
        ),
        "input_file_scopes": (
            "web/bootstrap/**/*.py",
            "web/error_boundary.py",
            "web/error_handlers.py",
            "web/ui_mode.py",
            "web/ui_mode_request.py",
            "web/ui_mode_store.py",
            "web/render_bridge.py",
            "web/manual_src_security.py",
            # P0.2：登记 web/ 顶层请求基础设施文件，避免改它们时因「不属任何组」升全量（从 4 降到 1）。
            "web/__init__.py",
            "web/navigation_context.py",
            "web/request_resource_context.py",
            "web/routes/**/*.py",
            "web/bootstrap/*.py",
            "web/routes/__init__.py",
            "web/routes/navigation_utils.py",
            "web/routes/normalizers.py",
            "web/routes/system_utils.py",
            "web/routes/system_backup.py",
            "web/routes/system_history.py",
            "web/routes/system_logs.py",
            "web/routes/system_plugins.py",
            "web/routes/system_ui_mode.py",
            "web/routes/domains/scheduler/scheduler_config.py",
            "web/routes/domains/scheduler/scheduler_batches.py",
            # P0.3 收窄：core 收窄到 request/runtime/migration 相关子域（其余 core 由 run_core owner 覆盖）。
            # data/** 保留——迁移测试承重，本组是 data 的第二 owner。web/routes/** 与 plugins/** 保留
            # （本组是其 owner，且 web/routes/** 被契约 :171 PIN）。templates 收窄到 system 页面；
            # static 由 ui_layout owner 覆盖故移除。
            "core/infrastructure/**/*.py",
            "core/models/**/*.py",
            "core/services/common/**/*.py",
            "core/services/system/**/*.py",
            "data/**/*.py",
            "tests/operation_execution_migration_support.py",
            "plugins/**/*.py",
            "templates/system/**/*.html",
            "app.py",
            "app_new_ui.py",
            "config.py",
            "schema.sql",
        ),
        "env_keys": (
            "APS_ENV",
            "APS_DB_PATH",
            "APS_LOG_DIR",
            "APS_BACKUP_DIR",
            "APS_EXCEL_TEMPLATE_DIR",
            "APS_CHROME_PATH",
            "SECRET_KEY",
        ),
    },
    {
        "group_id": "frontend_manual_excel",
        "label": "Frontend manual and Excel contracts",
        "target_paths": (
            "tests/test_excel_import_hardening.py",
            "tests/test_excel_utils_compare_digest_guard.py",
            "tests/regression_excel_conversion_output_contracts.py",
            "tests/regression_excel_hidden_payload_contract.py",
            "tests/regression_frontend_offline_static_assets.py",
            "tests/test_excel_renamed_column_conflicts.py",
            "tests/regression_import_execution_stats_source_row_num.py",
        ),
        "input_file_scopes": (
            "templates_excel/**/*",
            # P0.3 收窄：本组是 templates_excel 的 owner（保留宽 glob）。docs 三项保留原样
            # （文档改动本就 skip 门禁、且 test_long_gate_required_regression_cache 契约要求其存在）；
            # templates 收窄到 excel 导入页面；viewmodels 收窄到 excel 域；core 收窄到导入相关服务子域；
            # static/web_new_test(非docs) 由 ui_layout owner 覆盖故移除；data 由 run_core owner 覆盖故移除。
            "docs/**/*.md",
            "static/docs/**/*.md",
            "web_new_test/static/docs/**/*.md",
            "templates/excel/**/*.html",
            "templates/scheduler/excel_import*.html",
            "templates/components/excel*.html",
            "templates/equipment/excel_import*.html",
            "web/routes/excel_*.py",
            "web/routes/process_excel_*.py",
            "web/routes/personnel_excel_*.py",
            "web/routes/equipment_excel_*.py",
            "web/routes/domains/scheduler/scheduler_excel*.py",
            "web/routes/domains/scheduler/scheduler_config_display_state.py",
            "web/routes/scheduler_excel*.py",
            "web/manual_src_security.py",
            "web/render_bridge.py",
            "web/viewmodels/excel_entry_cards.py",
            "web/viewmodels/page_manuals*.py",
            "core/services/process/**/*.py",
            "core/services/common/**/*.py",
            "core/services/material/**/*.py",
            "core/services/personnel/**/*.py",
            "core/services/equipment/**/*.py",
            "app.py",
            "app_new_ui.py",
            "config.py",
            "schema.sql",
        ),
        "env_keys": (
            "APS_ENV",
            "APS_DB_PATH",
            "APS_EXCEL_TEMPLATE_DIR",
            "APS_CHROME_PATH",
            "APS_STATIC_VERSION",
            "node_executable_realpath",
            "node_version",
        ),
    },
    {
        "group_id": "ui_layout_presenters_system",
        "label": "UI layout, presenters, and system contracts",
        "target_paths": (
            "tests/regression_system_history_route_contract.py",
            "tests/test_ui_browser_geometry_env.py",
            "tests/test_ui_geometry_html_contract.py",
            "tests/test_scan_py38plus_syntax.py",
            "tests/test_architecture_fitness.py",
            "tests/regression_workbench_nav_entry_contract.py",
        ),
        "input_file_scopes": (
            "tests/ui_geometry_contract_data.py",
            "tests/ui_geometry_runtime_support.py",
            "tests/ui_geometry_browser_support.py",
            "tests/ui_geometry_probe.mjs",
            "tests/ui_geometry_cdp_client.mjs",
            "tests/ui_geometry_probe_page_eval.mjs",
            "templates/**/*.html",
            "web_new_test/templates/**/*.html",
            "static/**/*",
            "web_new_test/static/**/*",
            # P0.3 收窄：整树 web/viewmodels 由 analysis owner 覆盖、core/data 由 run_core owner 覆盖故移除；
            # 但保留本组真正测的 system/presenter viewmodels 窄 glob——ui_layout 的整页渲染契约受这些
            # viewmodel 影响，须随它们变动在 push 时触发（红队 item8）；本组是 templates/static 的 owner
            # （上方保留宽 glob），不再被无关 core/其他 viewmodel 逻辑改动拖入慢浏览器几何测试。
            "web/viewmodels/system_*.py",
            "web/viewmodels/ui_presenters.py",
            "web/routes/system_*.py",
            "web/routes/system_backup.py",
            "web/routes/system_history.py",
            "web/routes/system_logs.py",
            "web/routes/system.py",
            "web/routes/system_bp.py",
            "web/routes/system_health.py",
            "web/routes/system_plugins.py",
            "web/routes/system_ui_mode.py",
            "web/routes/excel_utils.py",
            "web/routes/process_parts.py",
            "web/routes/process_excel_routes.py",
            "web/routes/domains/scheduler/scheduler_run.py",
            "web/routes/domains/scheduler/scheduler_batches.py",
            "web/routes/domains/scheduler/scheduler_batch_detail.py",
            "web/routes/domains/scheduler/scheduler_excel_batches.py",
            "web/routes/domains/scheduler/scheduler_week_plan.py",
            "app.py",
            "app_new_ui.py",
            "config.py",
            "schema.sql",
        ),
        "env_keys": (
            "APS_BROWSER_SMOKE_REQUIRED",
            "APS_CHROME_PATH",
            "APS_STATIC_VERSION",
            "CI",
            "node_executable_realpath",
            "node_version",
            "node_browser_runtime_capability",
            "NODE_OPTIONS",
        ),
    },
)
